// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/timber/v1/competition.proto

package timber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	common "npln.nintendo.net/npln-practice/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCompetitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	View          CompetitionView        `protobuf:"varint,2,opt,name=view,proto3,enum=nn.npln.timber.v1.CompetitionView" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionRequest) Reset() {
	*x = GetCompetitionRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionRequest) ProtoMessage() {}

func (x *GetCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{0}
}

func (x *GetCompetitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCompetitionRequest) GetView() CompetitionView {
	if x != nil {
		return x.View
	}
	return CompetitionView_COMPETITION_VIEW_UNSPECIFIED
}

type CreateCompetitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Competition   *Competition           `protobuf:"bytes,2,opt,name=competition,proto3" json:"competition,omitempty"`
	CompetitionId string                 `protobuf:"bytes,3,opt,name=competition_id,json=competitionId,proto3" json:"competition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompetitionRequest) Reset() {
	*x = CreateCompetitionRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompetitionRequest) ProtoMessage() {}

func (x *CreateCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompetitionRequest.ProtoReflect.Descriptor instead.
func (*CreateCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCompetitionRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateCompetitionRequest) GetCompetition() *Competition {
	if x != nil {
		return x.Competition
	}
	return nil
}

func (x *CreateCompetitionRequest) GetCompetitionId() string {
	if x != nil {
		return x.CompetitionId
	}
	return ""
}

type UpdateCompetitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Competition   *Competition           `protobuf:"bytes,1,opt,name=competition,proto3" json:"competition,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompetitionRequest) Reset() {
	*x = UpdateCompetitionRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompetitionRequest) ProtoMessage() {}

func (x *UpdateCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompetitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCompetitionRequest) GetCompetition() *Competition {
	if x != nil {
		return x.Competition
	}
	return nil
}

func (x *UpdateCompetitionRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteCompetitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompetitionRequest) Reset() {
	*x = DeleteCompetitionRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompetitionRequest) ProtoMessage() {}

func (x *DeleteCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompetitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCompetitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteCompetitionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type SearchCompetitionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tenant           string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	PageSize         int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken        string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View             int32                  `protobuf:"varint,4,opt,name=view,proto3" json:"view,omitempty"`
	CompetitionTypes []CompetitionType      `protobuf:"varint,6,rep,packed,name=competition_types,json=competitionTypes,proto3,enum=nn.npln.timber.v1.CompetitionType" json:"competition_types,omitempty"`
	QueryType        string                 `protobuf:"bytes,7,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	QueryParams      *common.MapValue       `protobuf:"bytes,8,opt,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchCompetitionsRequest) Reset() {
	*x = SearchCompetitionsRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCompetitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCompetitionsRequest) ProtoMessage() {}

func (x *SearchCompetitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCompetitionsRequest.ProtoReflect.Descriptor instead.
func (*SearchCompetitionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{4}
}

func (x *SearchCompetitionsRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *SearchCompetitionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchCompetitionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchCompetitionsRequest) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *SearchCompetitionsRequest) GetCompetitionTypes() []CompetitionType {
	if x != nil {
		return x.CompetitionTypes
	}
	return nil
}

func (x *SearchCompetitionsRequest) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *SearchCompetitionsRequest) GetQueryParams() *common.MapValue {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

type SearchCompetitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Competitions  []*Competition         `protobuf:"bytes,1,rep,name=competitions,proto3" json:"competitions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCompetitionsResponse) Reset() {
	*x = SearchCompetitionsResponse{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCompetitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCompetitionsResponse) ProtoMessage() {}

func (x *SearchCompetitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCompetitionsResponse.ProtoReflect.Descriptor instead.
func (*SearchCompetitionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{5}
}

func (x *SearchCompetitionsResponse) GetCompetitions() []*Competition {
	if x != nil {
		return x.Competitions
	}
	return nil
}

func (x *SearchCompetitionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type HostCompetitionRequest struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	Tenant                 string                  `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Competition            *Competition            `protobuf:"bytes,2,opt,name=competition,proto3" json:"competition,omitempty"`
	CompetitionParticipant *CompetitionParticipant `protobuf:"bytes,3,opt,name=competition_participant,json=competitionParticipant,proto3" json:"competition_participant,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HostCompetitionRequest) Reset() {
	*x = HostCompetitionRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCompetitionRequest) ProtoMessage() {}

func (x *HostCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCompetitionRequest.ProtoReflect.Descriptor instead.
func (*HostCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{6}
}

func (x *HostCompetitionRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *HostCompetitionRequest) GetCompetition() *Competition {
	if x != nil {
		return x.Competition
	}
	return nil
}

func (x *HostCompetitionRequest) GetCompetitionParticipant() *CompetitionParticipant {
	if x != nil {
		return x.CompetitionParticipant
	}
	return nil
}

type HostCompetitionResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Competition   *Competition            `protobuf:"bytes,1,opt,name=competition,proto3" json:"competition,omitempty"`
	Participant   *CompetitionParticipant `protobuf:"bytes,2,opt,name=participant,proto3" json:"participant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostCompetitionResponse) Reset() {
	*x = HostCompetitionResponse{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCompetitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCompetitionResponse) ProtoMessage() {}

func (x *HostCompetitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCompetitionResponse.ProtoReflect.Descriptor instead.
func (*HostCompetitionResponse) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{7}
}

func (x *HostCompetitionResponse) GetCompetition() *Competition {
	if x != nil {
		return x.Competition
	}
	return nil
}

func (x *HostCompetitionResponse) GetParticipant() *CompetitionParticipant {
	if x != nil {
		return x.Participant
	}
	return nil
}

type FinalizeCompetitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeCompetitionRequest) Reset() {
	*x = FinalizeCompetitionRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeCompetitionRequest) ProtoMessage() {}

func (x *FinalizeCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeCompetitionRequest.ProtoReflect.Descriptor instead.
func (*FinalizeCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{8}
}

func (x *FinalizeCompetitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FinalizeCompetitionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type GetCompetitionAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionAliasRequest) Reset() {
	*x = GetCompetitionAliasRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionAliasRequest) ProtoMessage() {}

func (x *GetCompetitionAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionAliasRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionAliasRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{9}
}

func (x *GetCompetitionAliasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCompetitionInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionInvitationRequest) Reset() {
	*x = GetCompetitionInvitationRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionInvitationRequest) ProtoMessage() {}

func (x *GetCompetitionInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionInvitationRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionInvitationRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{10}
}

func (x *GetCompetitionInvitationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCompetitionInvitationRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Parent                  string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	CompetitionInvitation   *CompetitionInvitation `protobuf:"bytes,2,opt,name=competition_invitation,json=competitionInvitation,proto3" json:"competition_invitation,omitempty"`
	CompetitionInvitationId string                 `protobuf:"bytes,3,opt,name=competition_invitation_id,json=competitionInvitationId,proto3" json:"competition_invitation_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CreateCompetitionInvitationRequest) Reset() {
	*x = CreateCompetitionInvitationRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompetitionInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompetitionInvitationRequest) ProtoMessage() {}

func (x *CreateCompetitionInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompetitionInvitationRequest.ProtoReflect.Descriptor instead.
func (*CreateCompetitionInvitationRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCompetitionInvitationRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateCompetitionInvitationRequest) GetCompetitionInvitation() *CompetitionInvitation {
	if x != nil {
		return x.CompetitionInvitation
	}
	return nil
}

func (x *CreateCompetitionInvitationRequest) GetCompetitionInvitationId() string {
	if x != nil {
		return x.CompetitionInvitationId
	}
	return ""
}

type ListCompetitionInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompetitionInvitationsRequest) Reset() {
	*x = ListCompetitionInvitationsRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompetitionInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompetitionInvitationsRequest) ProtoMessage() {}

func (x *ListCompetitionInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompetitionInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListCompetitionInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{12}
}

func (x *ListCompetitionInvitationsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListCompetitionInvitationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCompetitionInvitationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCompetitionInvitationsResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	CompetitionInvitations []*CompetitionInvitation `protobuf:"bytes,1,rep,name=competition_invitations,json=competitionInvitations,proto3" json:"competition_invitations,omitempty"`
	NextPageToken          string                   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListCompetitionInvitationsResponse) Reset() {
	*x = ListCompetitionInvitationsResponse{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompetitionInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompetitionInvitationsResponse) ProtoMessage() {}

func (x *ListCompetitionInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompetitionInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListCompetitionInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{13}
}

func (x *ListCompetitionInvitationsResponse) GetCompetitionInvitations() []*CompetitionInvitation {
	if x != nil {
		return x.CompetitionInvitations
	}
	return nil
}

func (x *ListCompetitionInvitationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteCompetitionInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompetitionInvitationRequest) Reset() {
	*x = DeleteCompetitionInvitationRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompetitionInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompetitionInvitationRequest) ProtoMessage() {}

func (x *DeleteCompetitionInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompetitionInvitationRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompetitionInvitationRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteCompetitionInvitationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BatchCreateCompetitionInvitationsRequest struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Parent        string                                `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Requests      []*CreateCompetitionInvitationRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateCompetitionInvitationsRequest) Reset() {
	*x = BatchCreateCompetitionInvitationsRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateCompetitionInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateCompetitionInvitationsRequest) ProtoMessage() {}

func (x *BatchCreateCompetitionInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateCompetitionInvitationsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateCompetitionInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{15}
}

func (x *BatchCreateCompetitionInvitationsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchCreateCompetitionInvitationsRequest) GetRequests() []*CreateCompetitionInvitationRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateCompetitionInvitationsResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	CompetitionInvitations []*CompetitionInvitation `protobuf:"bytes,1,rep,name=competition_invitations,json=competitionInvitations,proto3" json:"competition_invitations,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BatchCreateCompetitionInvitationsResponse) Reset() {
	*x = BatchCreateCompetitionInvitationsResponse{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateCompetitionInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateCompetitionInvitationsResponse) ProtoMessage() {}

func (x *BatchCreateCompetitionInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateCompetitionInvitationsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateCompetitionInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{16}
}

func (x *BatchCreateCompetitionInvitationsResponse) GetCompetitionInvitations() []*CompetitionInvitation {
	if x != nil {
		return x.CompetitionInvitations
	}
	return nil
}

type GetCompetitionParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionParticipantRequest) Reset() {
	*x = GetCompetitionParticipantRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionParticipantRequest) ProtoMessage() {}

func (x *GetCompetitionParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionParticipantRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionParticipantRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{17}
}

func (x *GetCompetitionParticipantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCompetitionParticipantRequest struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	Parent                 string                  `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	CompetitionParticipant *CompetitionParticipant `protobuf:"bytes,2,opt,name=competition_participant,json=competitionParticipant,proto3" json:"competition_participant,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateCompetitionParticipantRequest) Reset() {
	*x = CreateCompetitionParticipantRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompetitionParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompetitionParticipantRequest) ProtoMessage() {}

func (x *CreateCompetitionParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompetitionParticipantRequest.ProtoReflect.Descriptor instead.
func (*CreateCompetitionParticipantRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{18}
}

func (x *CreateCompetitionParticipantRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateCompetitionParticipantRequest) GetCompetitionParticipant() *CompetitionParticipant {
	if x != nil {
		return x.CompetitionParticipant
	}
	return nil
}

type ActivateCompetitionParticipantRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParticipantBinary *wrapperspb.BytesValue `protobuf:"bytes,2,opt,name=participant_binary,json=participantBinary,proto3" json:"participant_binary,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivateCompetitionParticipantRequest) Reset() {
	*x = ActivateCompetitionParticipantRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateCompetitionParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateCompetitionParticipantRequest) ProtoMessage() {}

func (x *ActivateCompetitionParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateCompetitionParticipantRequest.ProtoReflect.Descriptor instead.
func (*ActivateCompetitionParticipantRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{19}
}

func (x *ActivateCompetitionParticipantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivateCompetitionParticipantRequest) GetParticipantBinary() *wrapperspb.BytesValue {
	if x != nil {
		return x.ParticipantBinary
	}
	return nil
}

type DeactivateCompetitionParticipantRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParticipantBinary *wrapperspb.BytesValue `protobuf:"bytes,2,opt,name=participant_binary,json=participantBinary,proto3" json:"participant_binary,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeactivateCompetitionParticipantRequest) Reset() {
	*x = DeactivateCompetitionParticipantRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateCompetitionParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateCompetitionParticipantRequest) ProtoMessage() {}

func (x *DeactivateCompetitionParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateCompetitionParticipantRequest.ProtoReflect.Descriptor instead.
func (*DeactivateCompetitionParticipantRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{20}
}

func (x *DeactivateCompetitionParticipantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeactivateCompetitionParticipantRequest) GetParticipantBinary() *wrapperspb.BytesValue {
	if x != nil {
		return x.ParticipantBinary
	}
	return nil
}

type CancelCompetitionParticipantRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParticipantBinary *wrapperspb.BytesValue `protobuf:"bytes,2,opt,name=participant_binary,json=participantBinary,proto3" json:"participant_binary,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelCompetitionParticipantRequest) Reset() {
	*x = CancelCompetitionParticipantRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCompetitionParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCompetitionParticipantRequest) ProtoMessage() {}

func (x *CancelCompetitionParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCompetitionParticipantRequest.ProtoReflect.Descriptor instead.
func (*CancelCompetitionParticipantRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{21}
}

func (x *CancelCompetitionParticipantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CancelCompetitionParticipantRequest) GetParticipantBinary() *wrapperspb.BytesValue {
	if x != nil {
		return x.ParticipantBinary
	}
	return nil
}

type GetCompetitionNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionNotificationRequest) Reset() {
	*x = GetCompetitionNotificationRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionNotificationRequest) ProtoMessage() {}

func (x *GetCompetitionNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{22}
}

func (x *GetCompetitionNotificationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCompetitionNotificationRequest struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	CompetitionNotification *CompetitionNotification `protobuf:"bytes,1,opt,name=competition_notification,json=competitionNotification,proto3" json:"competition_notification,omitempty"`
	UpdateMask              *fieldmaskpb.FieldMask   `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateCompetitionNotificationRequest) Reset() {
	*x = UpdateCompetitionNotificationRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompetitionNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompetitionNotificationRequest) ProtoMessage() {}

func (x *UpdateCompetitionNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompetitionNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompetitionNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateCompetitionNotificationRequest) GetCompetitionNotification() *CompetitionNotification {
	if x != nil {
		return x.CompetitionNotification
	}
	return nil
}

func (x *UpdateCompetitionNotificationRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type ReceiveCompetitionNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveCompetitionNotificationRequest) Reset() {
	*x = ReceiveCompetitionNotificationRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveCompetitionNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveCompetitionNotificationRequest) ProtoMessage() {}

func (x *ReceiveCompetitionNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveCompetitionNotificationRequest.ProtoReflect.Descriptor instead.
func (*ReceiveCompetitionNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{24}
}

func (x *ReceiveCompetitionNotificationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReceiveCompetitionNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveCompetitionNotificationResponse) Reset() {
	*x = ReceiveCompetitionNotificationResponse{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveCompetitionNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveCompetitionNotificationResponse) ProtoMessage() {}

func (x *ReceiveCompetitionNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveCompetitionNotificationResponse.ProtoReflect.Descriptor instead.
func (*ReceiveCompetitionNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{25}
}

type InvalidateCompetitionNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ETag          string                 `protobuf:"bytes,2,opt,name=e_tag,json=eTag,proto3" json:"e_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCompetitionNotificationRequest) Reset() {
	*x = InvalidateCompetitionNotificationRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCompetitionNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCompetitionNotificationRequest) ProtoMessage() {}

func (x *InvalidateCompetitionNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCompetitionNotificationRequest.ProtoReflect.Descriptor instead.
func (*InvalidateCompetitionNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{26}
}

func (x *InvalidateCompetitionNotificationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InvalidateCompetitionNotificationRequest) GetETag() string {
	if x != nil {
		return x.ETag
	}
	return ""
}

type GetCompetitionUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionUserRequest) Reset() {
	*x = GetCompetitionUserRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionUserRequest) ProtoMessage() {}

func (x *GetCompetitionUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionUserRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{27}
}

func (x *GetCompetitionUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCompetitionUserRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type CreateCompetitionUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Parent          string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	CompetitionUser *CompetitionUser       `protobuf:"bytes,2,opt,name=competition_user,json=competitionUser,proto3" json:"competition_user,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCompetitionUserRequest) Reset() {
	*x = CreateCompetitionUserRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompetitionUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompetitionUserRequest) ProtoMessage() {}

func (x *CreateCompetitionUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompetitionUserRequest.ProtoReflect.Descriptor instead.
func (*CreateCompetitionUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{28}
}

func (x *CreateCompetitionUserRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateCompetitionUserRequest) GetCompetitionUser() *CompetitionUser {
	if x != nil {
		return x.CompetitionUser
	}
	return nil
}

type UpdateCompetitionUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompetitionUser *CompetitionUser       `protobuf:"bytes,1,opt,name=competition_user,json=competitionUser,proto3" json:"competition_user,omitempty"`
	UpdateMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateCompetitionUserRequest) Reset() {
	*x = UpdateCompetitionUserRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompetitionUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompetitionUserRequest) ProtoMessage() {}

func (x *UpdateCompetitionUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompetitionUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompetitionUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateCompetitionUserRequest) GetCompetitionUser() *CompetitionUser {
	if x != nil {
		return x.CompetitionUser
	}
	return nil
}

func (x *UpdateCompetitionUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type GetCompetitionUserBattleRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionUserBattleRecordRequest) Reset() {
	*x = GetCompetitionUserBattleRecordRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionUserBattleRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionUserBattleRecordRequest) ProtoMessage() {}

func (x *GetCompetitionUserBattleRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionUserBattleRecordRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionUserBattleRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{30}
}

func (x *GetCompetitionUserBattleRecordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCompetitionUserBattleRecordRequest struct {
	state                       protoimpl.MessageState       `protogen:"open.v1"`
	Parent                      string                       `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	CompetitionUserBattleRecord *CompetitionUserBattleRecord `protobuf:"bytes,2,opt,name=competition_user_battle_record,json=competitionUserBattleRecord,proto3" json:"competition_user_battle_record,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CreateCompetitionUserBattleRecordRequest) Reset() {
	*x = CreateCompetitionUserBattleRecordRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompetitionUserBattleRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompetitionUserBattleRecordRequest) ProtoMessage() {}

func (x *CreateCompetitionUserBattleRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompetitionUserBattleRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateCompetitionUserBattleRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{31}
}

func (x *CreateCompetitionUserBattleRecordRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateCompetitionUserBattleRecordRequest) GetCompetitionUserBattleRecord() *CompetitionUserBattleRecord {
	if x != nil {
		return x.CompetitionUserBattleRecord
	}
	return nil
}

type UpdateCompetitionUserBattleRecordRequest struct {
	state                       protoimpl.MessageState       `protogen:"open.v1"`
	CompetitionUserBattleRecord *CompetitionUserBattleRecord `protobuf:"bytes,1,opt,name=competition_user_battle_record,json=competitionUserBattleRecord,proto3" json:"competition_user_battle_record,omitempty"`
	UpdateMask                  *fieldmaskpb.FieldMask       `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UpdateCompetitionUserBattleRecordRequest) Reset() {
	*x = UpdateCompetitionUserBattleRecordRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompetitionUserBattleRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompetitionUserBattleRecordRequest) ProtoMessage() {}

func (x *UpdateCompetitionUserBattleRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompetitionUserBattleRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompetitionUserBattleRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateCompetitionUserBattleRecordRequest) GetCompetitionUserBattleRecord() *CompetitionUserBattleRecord {
	if x != nil {
		return x.CompetitionUserBattleRecord
	}
	return nil
}

func (x *UpdateCompetitionUserBattleRecordRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type FinishCompetitionUserBattleRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishCompetitionUserBattleRecordRequest) Reset() {
	*x = FinishCompetitionUserBattleRecordRequest{}
	mi := &file_proto_timber_v1_competition_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishCompetitionUserBattleRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishCompetitionUserBattleRecordRequest) ProtoMessage() {}

func (x *FinishCompetitionUserBattleRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_competition_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishCompetitionUserBattleRecordRequest.ProtoReflect.Descriptor instead.
func (*FinishCompetitionUserBattleRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_competition_proto_rawDescGZIP(), []int{33}
}

func (x *FinishCompetitionUserBattleRecordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_timber_v1_competition_proto protoreflect.FileDescriptor

const file_proto_timber_v1_competition_proto_rawDesc = "" +
	"\n" +
	"!proto/timber/v1/competition.proto\x12\x11nn.npln.timber.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x18proto/common/value.proto\x1a\x1fproto/timber/v1/resources.proto\"c\n" +
	"\x15GetCompetitionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\x04view\x18\x02 \x01(\x0e2\".nn.npln.timber.v1.CompetitionViewR\x04view\"\x9b\x01\n" +
	"\x18CreateCompetitionRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12@\n" +
	"\vcompetition\x18\x02 \x01(\v2\x1e.nn.npln.timber.v1.CompetitionR\vcompetition\x12%\n" +
	"\x0ecompetition_id\x18\x03 \x01(\tR\rcompetitionId\"\x99\x01\n" +
	"\x18UpdateCompetitionRequest\x12@\n" +
	"\vcompetition\x18\x01 \x01(\v2\x1e.nn.npln.timber.v1.CompetitionR\vcompetition\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"D\n" +
	"\x18DeleteCompetitionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\xb0\x02\n" +
	"\x19SearchCompetitionsRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x12\n" +
	"\x04view\x18\x04 \x01(\x05R\x04view\x12O\n" +
	"\x11competition_types\x18\x06 \x03(\x0e2\".nn.npln.timber.v1.CompetitionTypeR\x10competitionTypes\x12\x1d\n" +
	"\n" +
	"query_type\x18\a \x01(\tR\tqueryType\x12;\n" +
	"\fquery_params\x18\b \x01(\v2\x18.nn.npln.common.MapValueR\vqueryParams\"\x88\x01\n" +
	"\x1aSearchCompetitionsResponse\x12B\n" +
	"\fcompetitions\x18\x01 \x03(\v2\x1e.nn.npln.timber.v1.CompetitionR\fcompetitions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd6\x01\n" +
	"\x16HostCompetitionRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12@\n" +
	"\vcompetition\x18\x02 \x01(\v2\x1e.nn.npln.timber.v1.CompetitionR\vcompetition\x12b\n" +
	"\x17competition_participant\x18\x03 \x01(\v2).nn.npln.timber.v1.CompetitionParticipantR\x16competitionParticipant\"\xa8\x01\n" +
	"\x17HostCompetitionResponse\x12@\n" +
	"\vcompetition\x18\x01 \x01(\v2\x1e.nn.npln.timber.v1.CompetitionR\vcompetition\x12K\n" +
	"\vparticipant\x18\x02 \x01(\v2).nn.npln.timber.v1.CompetitionParticipantR\vparticipant\"F\n" +
	"\x1aFinalizeCompetitionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"0\n" +
	"\x1aGetCompetitionAliasRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\x1fGetCompetitionInvitationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xd9\x01\n" +
	"\"CreateCompetitionInvitationRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12_\n" +
	"\x16competition_invitation\x18\x02 \x01(\v2(.nn.npln.timber.v1.CompetitionInvitationR\x15competitionInvitation\x12:\n" +
	"\x19competition_invitation_id\x18\x03 \x01(\tR\x17competitionInvitationId\"w\n" +
	"!ListCompetitionInvitationsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xaf\x01\n" +
	"\"ListCompetitionInvitationsResponse\x12a\n" +
	"\x17competition_invitations\x18\x01 \x03(\v2(.nn.npln.timber.v1.CompetitionInvitationR\x16competitionInvitations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"8\n" +
	"\"DeleteCompetitionInvitationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x95\x01\n" +
	"(BatchCreateCompetitionInvitationsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12Q\n" +
	"\brequests\x18\x02 \x03(\v25.nn.npln.timber.v1.CreateCompetitionInvitationRequestR\brequests\"\x8e\x01\n" +
	")BatchCreateCompetitionInvitationsResponse\x12a\n" +
	"\x17competition_invitations\x18\x01 \x03(\v2(.nn.npln.timber.v1.CompetitionInvitationR\x16competitionInvitations\"6\n" +
	" GetCompetitionParticipantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa1\x01\n" +
	"#CreateCompetitionParticipantRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12b\n" +
	"\x17competition_participant\x18\x02 \x01(\v2).nn.npln.timber.v1.CompetitionParticipantR\x16competitionParticipant\"\x87\x01\n" +
	"%ActivateCompetitionParticipantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12J\n" +
	"\x12participant_binary\x18\x02 \x01(\v2\x1b.google.protobuf.BytesValueR\x11participantBinary\"\x89\x01\n" +
	"'DeactivateCompetitionParticipantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12J\n" +
	"\x12participant_binary\x18\x02 \x01(\v2\x1b.google.protobuf.BytesValueR\x11participantBinary\"\x85\x01\n" +
	"#CancelCompetitionParticipantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12J\n" +
	"\x12participant_binary\x18\x02 \x01(\v2\x1b.google.protobuf.BytesValueR\x11participantBinary\"7\n" +
	"!GetCompetitionNotificationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xca\x01\n" +
	"$UpdateCompetitionNotificationRequest\x12e\n" +
	"\x18competition_notification\x18\x01 \x01(\v2*.nn.npln.timber.v1.CompetitionNotificationR\x17competitionNotification\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\";\n" +
	"%ReceiveCompetitionNotificationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"&ReceiveCompetitionNotificationResponse\"S\n" +
	"(InvalidateCompetitionNotificationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x13\n" +
	"\x05e_tag\x18\x02 \x01(\tR\x04eTag\"h\n" +
	"\x19GetCompetitionUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\x85\x01\n" +
	"\x1cCreateCompetitionUserRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12M\n" +
	"\x10competition_user\x18\x02 \x01(\v2\".nn.npln.timber.v1.CompetitionUserR\x0fcompetitionUser\"\xaa\x01\n" +
	"\x1cUpdateCompetitionUserRequest\x12M\n" +
	"\x10competition_user\x18\x01 \x01(\v2\".nn.npln.timber.v1.CompetitionUserR\x0fcompetitionUser\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\";\n" +
	"%GetCompetitionUserBattleRecordRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xb7\x01\n" +
	"(CreateCompetitionUserBattleRecordRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12s\n" +
	"\x1ecompetition_user_battle_record\x18\x02 \x01(\v2..nn.npln.timber.v1.CompetitionUserBattleRecordR\x1bcompetitionUserBattleRecord\"\xdc\x01\n" +
	"(UpdateCompetitionUserBattleRecordRequest\x12s\n" +
	"\x1ecompetition_user_battle_record\x18\x01 \x01(\v2..nn.npln.timber.v1.CompetitionUserBattleRecordR\x1bcompetitionUserBattleRecord\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\">\n" +
	"(FinishCompetitionUserBattleRecordRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xa4\x1c\n" +
	"\x12CompetitionService\x12Z\n" +
	"\x0eGetCompetition\x12(.nn.npln.timber.v1.GetCompetitionRequest\x1a\x1e.nn.npln.timber.v1.Competition\x12`\n" +
	"\x11CreateCompetition\x12+.nn.npln.timber.v1.CreateCompetitionRequest\x1a\x1e.nn.npln.timber.v1.Competition\x12`\n" +
	"\x11UpdateCompetition\x12+.nn.npln.timber.v1.UpdateCompetitionRequest\x1a\x1e.nn.npln.timber.v1.Competition\x12X\n" +
	"\x11DeleteCompetition\x12+.nn.npln.timber.v1.DeleteCompetitionRequest\x1a\x16.google.protobuf.Empty\x12q\n" +
	"\x12SearchCompetitions\x12,.nn.npln.timber.v1.SearchCompetitionsRequest\x1a-.nn.npln.timber.v1.SearchCompetitionsResponse\x12h\n" +
	"\x0fHostCompetition\x12).nn.npln.timber.v1.HostCompetitionRequest\x1a*.nn.npln.timber.v1.HostCompetitionResponse\x12d\n" +
	"\x13FinalizeCompetition\x12-.nn.npln.timber.v1.FinalizeCompetitionRequest\x1a\x1e.nn.npln.timber.v1.Competition\x12i\n" +
	"\x13GetCompetitionAlias\x12-.nn.npln.timber.v1.GetCompetitionAliasRequest\x1a#.nn.npln.timber.v1.CompetitionAlias\x12x\n" +
	"\x18GetCompetitionInvitation\x122.nn.npln.timber.v1.GetCompetitionInvitationRequest\x1a(.nn.npln.timber.v1.CompetitionInvitation\x12~\n" +
	"\x1bCreateCompetitionInvitation\x125.nn.npln.timber.v1.CreateCompetitionInvitationRequest\x1a(.nn.npln.timber.v1.CompetitionInvitation\x12\x89\x01\n" +
	"\x1aListCompetitionInvitations\x124.nn.npln.timber.v1.ListCompetitionInvitationsRequest\x1a5.nn.npln.timber.v1.ListCompetitionInvitationsResponse\x12l\n" +
	"\x1bDeleteCompetitionInvitation\x125.nn.npln.timber.v1.DeleteCompetitionInvitationRequest\x1a\x16.google.protobuf.Empty\x12\x9e\x01\n" +
	"!BatchCreateCompetitionInvitations\x12;.nn.npln.timber.v1.BatchCreateCompetitionInvitationsRequest\x1a<.nn.npln.timber.v1.BatchCreateCompetitionInvitationsResponse\x12{\n" +
	"\x19GetCompetitionParticipant\x123.nn.npln.timber.v1.GetCompetitionParticipantRequest\x1a).nn.npln.timber.v1.CompetitionParticipant\x12\x81\x01\n" +
	"\x1cCreateCompetitionParticipant\x126.nn.npln.timber.v1.CreateCompetitionParticipantRequest\x1a).nn.npln.timber.v1.CompetitionParticipant\x12\x85\x01\n" +
	"\x1eActivateCompetitionParticipant\x128.nn.npln.timber.v1.ActivateCompetitionParticipantRequest\x1a).nn.npln.timber.v1.CompetitionParticipant\x12\x89\x01\n" +
	" DeactivateCompetitionParticipant\x12:.nn.npln.timber.v1.DeactivateCompetitionParticipantRequest\x1a).nn.npln.timber.v1.CompetitionParticipant\x12\x81\x01\n" +
	"\x1cCancelCompetitionParticipant\x126.nn.npln.timber.v1.CancelCompetitionParticipantRequest\x1a).nn.npln.timber.v1.CompetitionParticipant\x12~\n" +
	"\x1aGetCompetitionNotification\x124.nn.npln.timber.v1.GetCompetitionNotificationRequest\x1a*.nn.npln.timber.v1.CompetitionNotification\x12\x84\x01\n" +
	"\x1dUpdateCompetitionNotification\x127.nn.npln.timber.v1.UpdateCompetitionNotificationRequest\x1a*.nn.npln.timber.v1.CompetitionNotification\x12\x97\x01\n" +
	"\x1eReceiveCompetitionNotification\x128.nn.npln.timber.v1.ReceiveCompetitionNotificationRequest\x1a9.nn.npln.timber.v1.ReceiveCompetitionNotificationResponse0\x01\x12\x8c\x01\n" +
	"!InvalidateCompetitionNotification\x12;.nn.npln.timber.v1.InvalidateCompetitionNotificationRequest\x1a*.nn.npln.timber.v1.CompetitionNotification\x12f\n" +
	"\x12GetCompetitionUser\x12,.nn.npln.timber.v1.GetCompetitionUserRequest\x1a\".nn.npln.timber.v1.CompetitionUser\x12l\n" +
	"\x15CreateCompetitionUser\x12/.nn.npln.timber.v1.CreateCompetitionUserRequest\x1a\".nn.npln.timber.v1.CompetitionUser\x12l\n" +
	"\x15UpdateCompetitionUser\x12/.nn.npln.timber.v1.UpdateCompetitionUserRequest\x1a\".nn.npln.timber.v1.CompetitionUser\x12\x8a\x01\n" +
	"\x1eGetCompetitionUserBattleRecord\x128.nn.npln.timber.v1.GetCompetitionUserBattleRecordRequest\x1a..nn.npln.timber.v1.CompetitionUserBattleRecord\x12\x90\x01\n" +
	"!CreateCompetitionUserBattleRecord\x12;.nn.npln.timber.v1.CreateCompetitionUserBattleRecordRequest\x1a..nn.npln.timber.v1.CompetitionUserBattleRecord\x12\x90\x01\n" +
	"!UpdateCompetitionUserBattleRecord\x12;.nn.npln.timber.v1.UpdateCompetitionUserBattleRecordRequest\x1a..nn.npln.timber.v1.CompetitionUserBattleRecord\x12\x90\x01\n" +
	"!FinishCompetitionUserBattleRecord\x12;.nn.npln.timber.v1.FinishCompetitionUserBattleRecordRequest\x1a..nn.npln.timber.v1.CompetitionUserBattleRecordB8Z6npln.nintendo.net/npln-practice/proto/timber/v1;timberb\x06proto3"

var (
	file_proto_timber_v1_competition_proto_rawDescOnce sync.Once
	file_proto_timber_v1_competition_proto_rawDescData []byte
)

func file_proto_timber_v1_competition_proto_rawDescGZIP() []byte {
	file_proto_timber_v1_competition_proto_rawDescOnce.Do(func() {
		file_proto_timber_v1_competition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_timber_v1_competition_proto_rawDesc), len(file_proto_timber_v1_competition_proto_rawDesc)))
	})
	return file_proto_timber_v1_competition_proto_rawDescData
}

var file_proto_timber_v1_competition_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_proto_timber_v1_competition_proto_goTypes = []any{
	(*GetCompetitionRequest)(nil),                     // 0: nn.npln.timber.v1.GetCompetitionRequest
	(*CreateCompetitionRequest)(nil),                  // 1: nn.npln.timber.v1.CreateCompetitionRequest
	(*UpdateCompetitionRequest)(nil),                  // 2: nn.npln.timber.v1.UpdateCompetitionRequest
	(*DeleteCompetitionRequest)(nil),                  // 3: nn.npln.timber.v1.DeleteCompetitionRequest
	(*SearchCompetitionsRequest)(nil),                 // 4: nn.npln.timber.v1.SearchCompetitionsRequest
	(*SearchCompetitionsResponse)(nil),                // 5: nn.npln.timber.v1.SearchCompetitionsResponse
	(*HostCompetitionRequest)(nil),                    // 6: nn.npln.timber.v1.HostCompetitionRequest
	(*HostCompetitionResponse)(nil),                   // 7: nn.npln.timber.v1.HostCompetitionResponse
	(*FinalizeCompetitionRequest)(nil),                // 8: nn.npln.timber.v1.FinalizeCompetitionRequest
	(*GetCompetitionAliasRequest)(nil),                // 9: nn.npln.timber.v1.GetCompetitionAliasRequest
	(*GetCompetitionInvitationRequest)(nil),           // 10: nn.npln.timber.v1.GetCompetitionInvitationRequest
	(*CreateCompetitionInvitationRequest)(nil),        // 11: nn.npln.timber.v1.CreateCompetitionInvitationRequest
	(*ListCompetitionInvitationsRequest)(nil),         // 12: nn.npln.timber.v1.ListCompetitionInvitationsRequest
	(*ListCompetitionInvitationsResponse)(nil),        // 13: nn.npln.timber.v1.ListCompetitionInvitationsResponse
	(*DeleteCompetitionInvitationRequest)(nil),        // 14: nn.npln.timber.v1.DeleteCompetitionInvitationRequest
	(*BatchCreateCompetitionInvitationsRequest)(nil),  // 15: nn.npln.timber.v1.BatchCreateCompetitionInvitationsRequest
	(*BatchCreateCompetitionInvitationsResponse)(nil), // 16: nn.npln.timber.v1.BatchCreateCompetitionInvitationsResponse
	(*GetCompetitionParticipantRequest)(nil),          // 17: nn.npln.timber.v1.GetCompetitionParticipantRequest
	(*CreateCompetitionParticipantRequest)(nil),       // 18: nn.npln.timber.v1.CreateCompetitionParticipantRequest
	(*ActivateCompetitionParticipantRequest)(nil),     // 19: nn.npln.timber.v1.ActivateCompetitionParticipantRequest
	(*DeactivateCompetitionParticipantRequest)(nil),   // 20: nn.npln.timber.v1.DeactivateCompetitionParticipantRequest
	(*CancelCompetitionParticipantRequest)(nil),       // 21: nn.npln.timber.v1.CancelCompetitionParticipantRequest
	(*GetCompetitionNotificationRequest)(nil),         // 22: nn.npln.timber.v1.GetCompetitionNotificationRequest
	(*UpdateCompetitionNotificationRequest)(nil),      // 23: nn.npln.timber.v1.UpdateCompetitionNotificationRequest
	(*ReceiveCompetitionNotificationRequest)(nil),     // 24: nn.npln.timber.v1.ReceiveCompetitionNotificationRequest
	(*ReceiveCompetitionNotificationResponse)(nil),    // 25: nn.npln.timber.v1.ReceiveCompetitionNotificationResponse
	(*InvalidateCompetitionNotificationRequest)(nil),  // 26: nn.npln.timber.v1.InvalidateCompetitionNotificationRequest
	(*GetCompetitionUserRequest)(nil),                 // 27: nn.npln.timber.v1.GetCompetitionUserRequest
	(*CreateCompetitionUserRequest)(nil),              // 28: nn.npln.timber.v1.CreateCompetitionUserRequest
	(*UpdateCompetitionUserRequest)(nil),              // 29: nn.npln.timber.v1.UpdateCompetitionUserRequest
	(*GetCompetitionUserBattleRecordRequest)(nil),     // 30: nn.npln.timber.v1.GetCompetitionUserBattleRecordRequest
	(*CreateCompetitionUserBattleRecordRequest)(nil),  // 31: nn.npln.timber.v1.CreateCompetitionUserBattleRecordRequest
	(*UpdateCompetitionUserBattleRecordRequest)(nil),  // 32: nn.npln.timber.v1.UpdateCompetitionUserBattleRecordRequest
	(*FinishCompetitionUserBattleRecordRequest)(nil),  // 33: nn.npln.timber.v1.FinishCompetitionUserBattleRecordRequest
	(CompetitionView)(0),                              // 34: nn.npln.timber.v1.CompetitionView
	(*Competition)(nil),                               // 35: nn.npln.timber.v1.Competition
	(*fieldmaskpb.FieldMask)(nil),                     // 36: google.protobuf.FieldMask
	(CompetitionType)(0),                              // 37: nn.npln.timber.v1.CompetitionType
	(*common.MapValue)(nil),                           // 38: nn.npln.common.MapValue
	(*CompetitionParticipant)(nil),                    // 39: nn.npln.timber.v1.CompetitionParticipant
	(*CompetitionInvitation)(nil),                     // 40: nn.npln.timber.v1.CompetitionInvitation
	(*wrapperspb.BytesValue)(nil),                     // 41: google.protobuf.BytesValue
	(*CompetitionNotification)(nil),                   // 42: nn.npln.timber.v1.CompetitionNotification
	(*CompetitionUser)(nil),                           // 43: nn.npln.timber.v1.CompetitionUser
	(*CompetitionUserBattleRecord)(nil),               // 44: nn.npln.timber.v1.CompetitionUserBattleRecord
	(*emptypb.Empty)(nil),                             // 45: google.protobuf.Empty
	(*CompetitionAlias)(nil),                          // 46: nn.npln.timber.v1.CompetitionAlias
}
var file_proto_timber_v1_competition_proto_depIdxs = []int32{
	34, // 0: nn.npln.timber.v1.GetCompetitionRequest.view:type_name -> nn.npln.timber.v1.CompetitionView
	35, // 1: nn.npln.timber.v1.CreateCompetitionRequest.competition:type_name -> nn.npln.timber.v1.Competition
	35, // 2: nn.npln.timber.v1.UpdateCompetitionRequest.competition:type_name -> nn.npln.timber.v1.Competition
	36, // 3: nn.npln.timber.v1.UpdateCompetitionRequest.update_mask:type_name -> google.protobuf.FieldMask
	37, // 4: nn.npln.timber.v1.SearchCompetitionsRequest.competition_types:type_name -> nn.npln.timber.v1.CompetitionType
	38, // 5: nn.npln.timber.v1.SearchCompetitionsRequest.query_params:type_name -> nn.npln.common.MapValue
	35, // 6: nn.npln.timber.v1.SearchCompetitionsResponse.competitions:type_name -> nn.npln.timber.v1.Competition
	35, // 7: nn.npln.timber.v1.HostCompetitionRequest.competition:type_name -> nn.npln.timber.v1.Competition
	39, // 8: nn.npln.timber.v1.HostCompetitionRequest.competition_participant:type_name -> nn.npln.timber.v1.CompetitionParticipant
	35, // 9: nn.npln.timber.v1.HostCompetitionResponse.competition:type_name -> nn.npln.timber.v1.Competition
	39, // 10: nn.npln.timber.v1.HostCompetitionResponse.participant:type_name -> nn.npln.timber.v1.CompetitionParticipant
	40, // 11: nn.npln.timber.v1.CreateCompetitionInvitationRequest.competition_invitation:type_name -> nn.npln.timber.v1.CompetitionInvitation
	40, // 12: nn.npln.timber.v1.ListCompetitionInvitationsResponse.competition_invitations:type_name -> nn.npln.timber.v1.CompetitionInvitation
	11, // 13: nn.npln.timber.v1.BatchCreateCompetitionInvitationsRequest.requests:type_name -> nn.npln.timber.v1.CreateCompetitionInvitationRequest
	40, // 14: nn.npln.timber.v1.BatchCreateCompetitionInvitationsResponse.competition_invitations:type_name -> nn.npln.timber.v1.CompetitionInvitation
	39, // 15: nn.npln.timber.v1.CreateCompetitionParticipantRequest.competition_participant:type_name -> nn.npln.timber.v1.CompetitionParticipant
	41, // 16: nn.npln.timber.v1.ActivateCompetitionParticipantRequest.participant_binary:type_name -> google.protobuf.BytesValue
	41, // 17: nn.npln.timber.v1.DeactivateCompetitionParticipantRequest.participant_binary:type_name -> google.protobuf.BytesValue
	41, // 18: nn.npln.timber.v1.CancelCompetitionParticipantRequest.participant_binary:type_name -> google.protobuf.BytesValue
	42, // 19: nn.npln.timber.v1.UpdateCompetitionNotificationRequest.competition_notification:type_name -> nn.npln.timber.v1.CompetitionNotification
	36, // 20: nn.npln.timber.v1.UpdateCompetitionNotificationRequest.update_mask:type_name -> google.protobuf.FieldMask
	36, // 21: nn.npln.timber.v1.GetCompetitionUserRequest.read_mask:type_name -> google.protobuf.FieldMask
	43, // 22: nn.npln.timber.v1.CreateCompetitionUserRequest.competition_user:type_name -> nn.npln.timber.v1.CompetitionUser
	43, // 23: nn.npln.timber.v1.UpdateCompetitionUserRequest.competition_user:type_name -> nn.npln.timber.v1.CompetitionUser
	36, // 24: nn.npln.timber.v1.UpdateCompetitionUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	44, // 25: nn.npln.timber.v1.CreateCompetitionUserBattleRecordRequest.competition_user_battle_record:type_name -> nn.npln.timber.v1.CompetitionUserBattleRecord
	44, // 26: nn.npln.timber.v1.UpdateCompetitionUserBattleRecordRequest.competition_user_battle_record:type_name -> nn.npln.timber.v1.CompetitionUserBattleRecord
	36, // 27: nn.npln.timber.v1.UpdateCompetitionUserBattleRecordRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 28: nn.npln.timber.v1.CompetitionService.GetCompetition:input_type -> nn.npln.timber.v1.GetCompetitionRequest
	1,  // 29: nn.npln.timber.v1.CompetitionService.CreateCompetition:input_type -> nn.npln.timber.v1.CreateCompetitionRequest
	2,  // 30: nn.npln.timber.v1.CompetitionService.UpdateCompetition:input_type -> nn.npln.timber.v1.UpdateCompetitionRequest
	3,  // 31: nn.npln.timber.v1.CompetitionService.DeleteCompetition:input_type -> nn.npln.timber.v1.DeleteCompetitionRequest
	4,  // 32: nn.npln.timber.v1.CompetitionService.SearchCompetitions:input_type -> nn.npln.timber.v1.SearchCompetitionsRequest
	6,  // 33: nn.npln.timber.v1.CompetitionService.HostCompetition:input_type -> nn.npln.timber.v1.HostCompetitionRequest
	8,  // 34: nn.npln.timber.v1.CompetitionService.FinalizeCompetition:input_type -> nn.npln.timber.v1.FinalizeCompetitionRequest
	9,  // 35: nn.npln.timber.v1.CompetitionService.GetCompetitionAlias:input_type -> nn.npln.timber.v1.GetCompetitionAliasRequest
	10, // 36: nn.npln.timber.v1.CompetitionService.GetCompetitionInvitation:input_type -> nn.npln.timber.v1.GetCompetitionInvitationRequest
	11, // 37: nn.npln.timber.v1.CompetitionService.CreateCompetitionInvitation:input_type -> nn.npln.timber.v1.CreateCompetitionInvitationRequest
	12, // 38: nn.npln.timber.v1.CompetitionService.ListCompetitionInvitations:input_type -> nn.npln.timber.v1.ListCompetitionInvitationsRequest
	14, // 39: nn.npln.timber.v1.CompetitionService.DeleteCompetitionInvitation:input_type -> nn.npln.timber.v1.DeleteCompetitionInvitationRequest
	15, // 40: nn.npln.timber.v1.CompetitionService.BatchCreateCompetitionInvitations:input_type -> nn.npln.timber.v1.BatchCreateCompetitionInvitationsRequest
	17, // 41: nn.npln.timber.v1.CompetitionService.GetCompetitionParticipant:input_type -> nn.npln.timber.v1.GetCompetitionParticipantRequest
	18, // 42: nn.npln.timber.v1.CompetitionService.CreateCompetitionParticipant:input_type -> nn.npln.timber.v1.CreateCompetitionParticipantRequest
	19, // 43: nn.npln.timber.v1.CompetitionService.ActivateCompetitionParticipant:input_type -> nn.npln.timber.v1.ActivateCompetitionParticipantRequest
	20, // 44: nn.npln.timber.v1.CompetitionService.DeactivateCompetitionParticipant:input_type -> nn.npln.timber.v1.DeactivateCompetitionParticipantRequest
	21, // 45: nn.npln.timber.v1.CompetitionService.CancelCompetitionParticipant:input_type -> nn.npln.timber.v1.CancelCompetitionParticipantRequest
	22, // 46: nn.npln.timber.v1.CompetitionService.GetCompetitionNotification:input_type -> nn.npln.timber.v1.GetCompetitionNotificationRequest
	23, // 47: nn.npln.timber.v1.CompetitionService.UpdateCompetitionNotification:input_type -> nn.npln.timber.v1.UpdateCompetitionNotificationRequest
	24, // 48: nn.npln.timber.v1.CompetitionService.ReceiveCompetitionNotification:input_type -> nn.npln.timber.v1.ReceiveCompetitionNotificationRequest
	26, // 49: nn.npln.timber.v1.CompetitionService.InvalidateCompetitionNotification:input_type -> nn.npln.timber.v1.InvalidateCompetitionNotificationRequest
	27, // 50: nn.npln.timber.v1.CompetitionService.GetCompetitionUser:input_type -> nn.npln.timber.v1.GetCompetitionUserRequest
	28, // 51: nn.npln.timber.v1.CompetitionService.CreateCompetitionUser:input_type -> nn.npln.timber.v1.CreateCompetitionUserRequest
	29, // 52: nn.npln.timber.v1.CompetitionService.UpdateCompetitionUser:input_type -> nn.npln.timber.v1.UpdateCompetitionUserRequest
	30, // 53: nn.npln.timber.v1.CompetitionService.GetCompetitionUserBattleRecord:input_type -> nn.npln.timber.v1.GetCompetitionUserBattleRecordRequest
	31, // 54: nn.npln.timber.v1.CompetitionService.CreateCompetitionUserBattleRecord:input_type -> nn.npln.timber.v1.CreateCompetitionUserBattleRecordRequest
	32, // 55: nn.npln.timber.v1.CompetitionService.UpdateCompetitionUserBattleRecord:input_type -> nn.npln.timber.v1.UpdateCompetitionUserBattleRecordRequest
	33, // 56: nn.npln.timber.v1.CompetitionService.FinishCompetitionUserBattleRecord:input_type -> nn.npln.timber.v1.FinishCompetitionUserBattleRecordRequest
	35, // 57: nn.npln.timber.v1.CompetitionService.GetCompetition:output_type -> nn.npln.timber.v1.Competition
	35, // 58: nn.npln.timber.v1.CompetitionService.CreateCompetition:output_type -> nn.npln.timber.v1.Competition
	35, // 59: nn.npln.timber.v1.CompetitionService.UpdateCompetition:output_type -> nn.npln.timber.v1.Competition
	45, // 60: nn.npln.timber.v1.CompetitionService.DeleteCompetition:output_type -> google.protobuf.Empty
	5,  // 61: nn.npln.timber.v1.CompetitionService.SearchCompetitions:output_type -> nn.npln.timber.v1.SearchCompetitionsResponse
	7,  // 62: nn.npln.timber.v1.CompetitionService.HostCompetition:output_type -> nn.npln.timber.v1.HostCompetitionResponse
	35, // 63: nn.npln.timber.v1.CompetitionService.FinalizeCompetition:output_type -> nn.npln.timber.v1.Competition
	46, // 64: nn.npln.timber.v1.CompetitionService.GetCompetitionAlias:output_type -> nn.npln.timber.v1.CompetitionAlias
	40, // 65: nn.npln.timber.v1.CompetitionService.GetCompetitionInvitation:output_type -> nn.npln.timber.v1.CompetitionInvitation
	40, // 66: nn.npln.timber.v1.CompetitionService.CreateCompetitionInvitation:output_type -> nn.npln.timber.v1.CompetitionInvitation
	13, // 67: nn.npln.timber.v1.CompetitionService.ListCompetitionInvitations:output_type -> nn.npln.timber.v1.ListCompetitionInvitationsResponse
	45, // 68: nn.npln.timber.v1.CompetitionService.DeleteCompetitionInvitation:output_type -> google.protobuf.Empty
	16, // 69: nn.npln.timber.v1.CompetitionService.BatchCreateCompetitionInvitations:output_type -> nn.npln.timber.v1.BatchCreateCompetitionInvitationsResponse
	39, // 70: nn.npln.timber.v1.CompetitionService.GetCompetitionParticipant:output_type -> nn.npln.timber.v1.CompetitionParticipant
	39, // 71: nn.npln.timber.v1.CompetitionService.CreateCompetitionParticipant:output_type -> nn.npln.timber.v1.CompetitionParticipant
	39, // 72: nn.npln.timber.v1.CompetitionService.ActivateCompetitionParticipant:output_type -> nn.npln.timber.v1.CompetitionParticipant
	39, // 73: nn.npln.timber.v1.CompetitionService.DeactivateCompetitionParticipant:output_type -> nn.npln.timber.v1.CompetitionParticipant
	39, // 74: nn.npln.timber.v1.CompetitionService.CancelCompetitionParticipant:output_type -> nn.npln.timber.v1.CompetitionParticipant
	42, // 75: nn.npln.timber.v1.CompetitionService.GetCompetitionNotification:output_type -> nn.npln.timber.v1.CompetitionNotification
	42, // 76: nn.npln.timber.v1.CompetitionService.UpdateCompetitionNotification:output_type -> nn.npln.timber.v1.CompetitionNotification
	25, // 77: nn.npln.timber.v1.CompetitionService.ReceiveCompetitionNotification:output_type -> nn.npln.timber.v1.ReceiveCompetitionNotificationResponse
	42, // 78: nn.npln.timber.v1.CompetitionService.InvalidateCompetitionNotification:output_type -> nn.npln.timber.v1.CompetitionNotification
	43, // 79: nn.npln.timber.v1.CompetitionService.GetCompetitionUser:output_type -> nn.npln.timber.v1.CompetitionUser
	43, // 80: nn.npln.timber.v1.CompetitionService.CreateCompetitionUser:output_type -> nn.npln.timber.v1.CompetitionUser
	43, // 81: nn.npln.timber.v1.CompetitionService.UpdateCompetitionUser:output_type -> nn.npln.timber.v1.CompetitionUser
	44, // 82: nn.npln.timber.v1.CompetitionService.GetCompetitionUserBattleRecord:output_type -> nn.npln.timber.v1.CompetitionUserBattleRecord
	44, // 83: nn.npln.timber.v1.CompetitionService.CreateCompetitionUserBattleRecord:output_type -> nn.npln.timber.v1.CompetitionUserBattleRecord
	44, // 84: nn.npln.timber.v1.CompetitionService.UpdateCompetitionUserBattleRecord:output_type -> nn.npln.timber.v1.CompetitionUserBattleRecord
	44, // 85: nn.npln.timber.v1.CompetitionService.FinishCompetitionUserBattleRecord:output_type -> nn.npln.timber.v1.CompetitionUserBattleRecord
	57, // [57:86] is the sub-list for method output_type
	28, // [28:57] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_timber_v1_competition_proto_init() }
func file_proto_timber_v1_competition_proto_init() {
	if File_proto_timber_v1_competition_proto != nil {
		return
	}
	file_proto_timber_v1_resources_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_timber_v1_competition_proto_rawDesc), len(file_proto_timber_v1_competition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_timber_v1_competition_proto_goTypes,
		DependencyIndexes: file_proto_timber_v1_competition_proto_depIdxs,
		MessageInfos:      file_proto_timber_v1_competition_proto_msgTypes,
	}.Build()
	File_proto_timber_v1_competition_proto = out.File
	file_proto_timber_v1_competition_proto_goTypes = nil
	file_proto_timber_v1_competition_proto_depIdxs = nil
}
