// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/timber/v1/trade_box.proto

package timber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTradeBoxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	TradeBox      *TradeBox              `protobuf:"bytes,2,opt,name=trade_box,json=tradeBox,proto3" json:"trade_box,omitempty"`
	TradeBoxId    string                 `protobuf:"bytes,3,opt,name=trade_box_id,json=tradeBoxId,proto3" json:"trade_box_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTradeBoxRequest) Reset() {
	*x = CreateTradeBoxRequest{}
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTradeBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeBoxRequest) ProtoMessage() {}

func (x *CreateTradeBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeBoxRequest.ProtoReflect.Descriptor instead.
func (*CreateTradeBoxRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_trade_box_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTradeBoxRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateTradeBoxRequest) GetTradeBox() *TradeBox {
	if x != nil {
		return x.TradeBox
	}
	return nil
}

func (x *CreateTradeBoxRequest) GetTradeBoxId() string {
	if x != nil {
		return x.TradeBoxId
	}
	return ""
}

type DeleteTradeBoxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTradeBoxRequest) Reset() {
	*x = DeleteTradeBoxRequest{}
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTradeBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTradeBoxRequest) ProtoMessage() {}

func (x *DeleteTradeBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTradeBoxRequest.ProtoReflect.Descriptor instead.
func (*DeleteTradeBoxRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_trade_box_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteTradeBoxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CancelTradeBoxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTradeBoxRequest) Reset() {
	*x = CancelTradeBoxRequest{}
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTradeBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTradeBoxRequest) ProtoMessage() {}

func (x *CancelTradeBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTradeBoxRequest.ProtoReflect.Descriptor instead.
func (*CancelTradeBoxRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_trade_box_proto_rawDescGZIP(), []int{2}
}

func (x *CancelTradeBoxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CancelTradeBoxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTradeBoxResponse) Reset() {
	*x = CancelTradeBoxResponse{}
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTradeBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTradeBoxResponse) ProtoMessage() {}

func (x *CancelTradeBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTradeBoxResponse.ProtoReflect.Descriptor instead.
func (*CancelTradeBoxResponse) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_trade_box_proto_rawDescGZIP(), []int{3}
}

type TrackTradeBoxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackTradeBoxRequest) Reset() {
	*x = TrackTradeBoxRequest{}
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackTradeBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackTradeBoxRequest) ProtoMessage() {}

func (x *TrackTradeBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackTradeBoxRequest.ProtoReflect.Descriptor instead.
func (*TrackTradeBoxRequest) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_trade_box_proto_rawDescGZIP(), []int{4}
}

func (x *TrackTradeBoxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TrackTradeBoxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeBox      *TradeBox              `protobuf:"bytes,1,opt,name=trade_box,json=tradeBox,proto3" json:"trade_box,omitempty"`
	Unk           bool                   `protobuf:"varint,2,opt,name=unk,proto3" json:"unk,omitempty"`
	KeepAlive     *KeepAlive             `protobuf:"bytes,3,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackTradeBoxResponse) Reset() {
	*x = TrackTradeBoxResponse{}
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackTradeBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackTradeBoxResponse) ProtoMessage() {}

func (x *TrackTradeBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timber_v1_trade_box_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackTradeBoxResponse.ProtoReflect.Descriptor instead.
func (*TrackTradeBoxResponse) Descriptor() ([]byte, []int) {
	return file_proto_timber_v1_trade_box_proto_rawDescGZIP(), []int{5}
}

func (x *TrackTradeBoxResponse) GetTradeBox() *TradeBox {
	if x != nil {
		return x.TradeBox
	}
	return nil
}

func (x *TrackTradeBoxResponse) GetUnk() bool {
	if x != nil {
		return x.Unk
	}
	return false
}

func (x *TrackTradeBoxResponse) GetKeepAlive() *KeepAlive {
	if x != nil {
		return x.KeepAlive
	}
	return nil
}

var File_proto_timber_v1_trade_box_proto protoreflect.FileDescriptor

const file_proto_timber_v1_trade_box_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/timber/v1/trade_box.proto\x12\x11nn.npln.timber.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cproto/timber/v1/common.proto\x1a\x1fproto/timber/v1/resources.proto\"\x8b\x01\n" +
	"\x15CreateTradeBoxRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x128\n" +
	"\ttrade_box\x18\x02 \x01(\v2\x1b.nn.npln.timber.v1.TradeBoxR\btradeBox\x12 \n" +
	"\ftrade_box_id\x18\x03 \x01(\tR\n" +
	"tradeBoxId\"+\n" +
	"\x15DeleteTradeBoxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x15CancelTradeBoxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16CancelTradeBoxResponse\"*\n" +
	"\x14TrackTradeBoxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa0\x01\n" +
	"\x15TrackTradeBoxResponse\x128\n" +
	"\ttrade_box\x18\x01 \x01(\v2\x1b.nn.npln.timber.v1.TradeBoxR\btradeBox\x12\x10\n" +
	"\x03unk\x18\x02 \x01(\bR\x03unk\x12;\n" +
	"\n" +
	"keep_alive\x18\x03 \x01(\v2\x1c.nn.npln.timber.v1.KeepAliveR\tkeepAlive2\x8b\x03\n" +
	"\x0fTradeBoxService\x12W\n" +
	"\x0eCreateTradeBox\x12(.nn.npln.timber.v1.CreateTradeBoxRequest\x1a\x1b.nn.npln.timber.v1.TradeBox\x12R\n" +
	"\x0eDeleteTradeBox\x12(.nn.npln.timber.v1.DeleteTradeBoxRequest\x1a\x16.google.protobuf.Empty\x12e\n" +
	"\x0eCancelTradeBox\x12(.nn.npln.timber.v1.CancelTradeBoxRequest\x1a).nn.npln.timber.v1.CancelTradeBoxResponse\x12d\n" +
	"\rTrackTradeBox\x12'.nn.npln.timber.v1.TrackTradeBoxRequest\x1a(.nn.npln.timber.v1.TrackTradeBoxResponse0\x01B8Z6npln.nintendo.net/npln-practice/proto/timber/v1;timberb\x06proto3"

var (
	file_proto_timber_v1_trade_box_proto_rawDescOnce sync.Once
	file_proto_timber_v1_trade_box_proto_rawDescData []byte
)

func file_proto_timber_v1_trade_box_proto_rawDescGZIP() []byte {
	file_proto_timber_v1_trade_box_proto_rawDescOnce.Do(func() {
		file_proto_timber_v1_trade_box_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_timber_v1_trade_box_proto_rawDesc), len(file_proto_timber_v1_trade_box_proto_rawDesc)))
	})
	return file_proto_timber_v1_trade_box_proto_rawDescData
}

var file_proto_timber_v1_trade_box_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_timber_v1_trade_box_proto_goTypes = []any{
	(*CreateTradeBoxRequest)(nil),  // 0: nn.npln.timber.v1.CreateTradeBoxRequest
	(*DeleteTradeBoxRequest)(nil),  // 1: nn.npln.timber.v1.DeleteTradeBoxRequest
	(*CancelTradeBoxRequest)(nil),  // 2: nn.npln.timber.v1.CancelTradeBoxRequest
	(*CancelTradeBoxResponse)(nil), // 3: nn.npln.timber.v1.CancelTradeBoxResponse
	(*TrackTradeBoxRequest)(nil),   // 4: nn.npln.timber.v1.TrackTradeBoxRequest
	(*TrackTradeBoxResponse)(nil),  // 5: nn.npln.timber.v1.TrackTradeBoxResponse
	(*TradeBox)(nil),               // 6: nn.npln.timber.v1.TradeBox
	(*KeepAlive)(nil),              // 7: nn.npln.timber.v1.KeepAlive
	(*emptypb.Empty)(nil),          // 8: google.protobuf.Empty
}
var file_proto_timber_v1_trade_box_proto_depIdxs = []int32{
	6, // 0: nn.npln.timber.v1.CreateTradeBoxRequest.trade_box:type_name -> nn.npln.timber.v1.TradeBox
	6, // 1: nn.npln.timber.v1.TrackTradeBoxResponse.trade_box:type_name -> nn.npln.timber.v1.TradeBox
	7, // 2: nn.npln.timber.v1.TrackTradeBoxResponse.keep_alive:type_name -> nn.npln.timber.v1.KeepAlive
	0, // 3: nn.npln.timber.v1.TradeBoxService.CreateTradeBox:input_type -> nn.npln.timber.v1.CreateTradeBoxRequest
	1, // 4: nn.npln.timber.v1.TradeBoxService.DeleteTradeBox:input_type -> nn.npln.timber.v1.DeleteTradeBoxRequest
	2, // 5: nn.npln.timber.v1.TradeBoxService.CancelTradeBox:input_type -> nn.npln.timber.v1.CancelTradeBoxRequest
	4, // 6: nn.npln.timber.v1.TradeBoxService.TrackTradeBox:input_type -> nn.npln.timber.v1.TrackTradeBoxRequest
	6, // 7: nn.npln.timber.v1.TradeBoxService.CreateTradeBox:output_type -> nn.npln.timber.v1.TradeBox
	8, // 8: nn.npln.timber.v1.TradeBoxService.DeleteTradeBox:output_type -> google.protobuf.Empty
	3, // 9: nn.npln.timber.v1.TradeBoxService.CancelTradeBox:output_type -> nn.npln.timber.v1.CancelTradeBoxResponse
	5, // 10: nn.npln.timber.v1.TradeBoxService.TrackTradeBox:output_type -> nn.npln.timber.v1.TrackTradeBoxResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_timber_v1_trade_box_proto_init() }
func file_proto_timber_v1_trade_box_proto_init() {
	if File_proto_timber_v1_trade_box_proto != nil {
		return
	}
	file_proto_timber_v1_common_proto_init()
	file_proto_timber_v1_resources_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_timber_v1_trade_box_proto_rawDesc), len(file_proto_timber_v1_trade_box_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_timber_v1_trade_box_proto_goTypes,
		DependencyIndexes: file_proto_timber_v1_trade_box_proto_depIdxs,
		MessageInfos:      file_proto_timber_v1_trade_box_proto_msgTypes,
	}.Build()
	File_proto_timber_v1_trade_box_proto = out.File
	file_proto_timber_v1_trade_box_proto_goTypes = nil
	file_proto_timber_v1_trade_box_proto_depIdxs = nil
}
