// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/timber/v1/trade_box.proto

package timber

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradeBoxService_CreateTradeBox_FullMethodName = "/nn.npln.timber.v1.TradeBoxService/CreateTradeBox"
	TradeBoxService_DeleteTradeBox_FullMethodName = "/nn.npln.timber.v1.TradeBoxService/DeleteTradeBox"
	TradeBoxService_CancelTradeBox_FullMethodName = "/nn.npln.timber.v1.TradeBoxService/CancelTradeBox"
	TradeBoxService_TrackTradeBox_FullMethodName  = "/nn.npln.timber.v1.TradeBoxService/TrackTradeBox"
)

// TradeBoxServiceClient is the client API for TradeBoxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeBoxServiceClient interface {
	CreateTradeBox(ctx context.Context, in *CreateTradeBoxRequest, opts ...grpc.CallOption) (*TradeBox, error)
	DeleteTradeBox(ctx context.Context, in *DeleteTradeBoxRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CancelTradeBox(ctx context.Context, in *CancelTradeBoxRequest, opts ...grpc.CallOption) (*CancelTradeBoxResponse, error)
	TrackTradeBox(ctx context.Context, in *TrackTradeBoxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrackTradeBoxResponse], error)
}

type tradeBoxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeBoxServiceClient(cc grpc.ClientConnInterface) TradeBoxServiceClient {
	return &tradeBoxServiceClient{cc}
}

func (c *tradeBoxServiceClient) CreateTradeBox(ctx context.Context, in *CreateTradeBoxRequest, opts ...grpc.CallOption) (*TradeBox, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeBox)
	err := c.cc.Invoke(ctx, TradeBoxService_CreateTradeBox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeBoxServiceClient) DeleteTradeBox(ctx context.Context, in *DeleteTradeBoxRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TradeBoxService_DeleteTradeBox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeBoxServiceClient) CancelTradeBox(ctx context.Context, in *CancelTradeBoxRequest, opts ...grpc.CallOption) (*CancelTradeBoxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTradeBoxResponse)
	err := c.cc.Invoke(ctx, TradeBoxService_CancelTradeBox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeBoxServiceClient) TrackTradeBox(ctx context.Context, in *TrackTradeBoxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrackTradeBoxResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TradeBoxService_ServiceDesc.Streams[0], TradeBoxService_TrackTradeBox_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrackTradeBoxRequest, TrackTradeBoxResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TradeBoxService_TrackTradeBoxClient = grpc.ServerStreamingClient[TrackTradeBoxResponse]

// TradeBoxServiceServer is the server API for TradeBoxService service.
// All implementations must embed UnimplementedTradeBoxServiceServer
// for forward compatibility.
type TradeBoxServiceServer interface {
	CreateTradeBox(context.Context, *CreateTradeBoxRequest) (*TradeBox, error)
	DeleteTradeBox(context.Context, *DeleteTradeBoxRequest) (*emptypb.Empty, error)
	CancelTradeBox(context.Context, *CancelTradeBoxRequest) (*CancelTradeBoxResponse, error)
	TrackTradeBox(*TrackTradeBoxRequest, grpc.ServerStreamingServer[TrackTradeBoxResponse]) error
	mustEmbedUnimplementedTradeBoxServiceServer()
}

// UnimplementedTradeBoxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeBoxServiceServer struct{}

func (UnimplementedTradeBoxServiceServer) CreateTradeBox(context.Context, *CreateTradeBoxRequest) (*TradeBox, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTradeBox not implemented")
}
func (UnimplementedTradeBoxServiceServer) DeleteTradeBox(context.Context, *DeleteTradeBoxRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTradeBox not implemented")
}
func (UnimplementedTradeBoxServiceServer) CancelTradeBox(context.Context, *CancelTradeBoxRequest) (*CancelTradeBoxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTradeBox not implemented")
}
func (UnimplementedTradeBoxServiceServer) TrackTradeBox(*TrackTradeBoxRequest, grpc.ServerStreamingServer[TrackTradeBoxResponse]) error {
	return status.Error(codes.Unimplemented, "method TrackTradeBox not implemented")
}
func (UnimplementedTradeBoxServiceServer) mustEmbedUnimplementedTradeBoxServiceServer() {}
func (UnimplementedTradeBoxServiceServer) testEmbeddedByValue()                         {}

// UnsafeTradeBoxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeBoxServiceServer will
// result in compilation errors.
type UnsafeTradeBoxServiceServer interface {
	mustEmbedUnimplementedTradeBoxServiceServer()
}

func RegisterTradeBoxServiceServer(s grpc.ServiceRegistrar, srv TradeBoxServiceServer) {
	// If the following call panics, it indicates UnimplementedTradeBoxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradeBoxService_ServiceDesc, srv)
}

func _TradeBoxService_CreateTradeBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeBoxServiceServer).CreateTradeBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeBoxService_CreateTradeBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeBoxServiceServer).CreateTradeBox(ctx, req.(*CreateTradeBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeBoxService_DeleteTradeBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTradeBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeBoxServiceServer).DeleteTradeBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeBoxService_DeleteTradeBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeBoxServiceServer).DeleteTradeBox(ctx, req.(*DeleteTradeBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeBoxService_CancelTradeBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTradeBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeBoxServiceServer).CancelTradeBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeBoxService_CancelTradeBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeBoxServiceServer).CancelTradeBox(ctx, req.(*CancelTradeBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeBoxService_TrackTradeBox_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrackTradeBoxRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TradeBoxServiceServer).TrackTradeBox(m, &grpc.GenericServerStream[TrackTradeBoxRequest, TrackTradeBoxResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TradeBoxService_TrackTradeBoxServer = grpc.ServerStreamingServer[TrackTradeBoxResponse]

// TradeBoxService_ServiceDesc is the grpc.ServiceDesc for TradeBoxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeBoxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nn.npln.timber.v1.TradeBoxService",
	HandlerType: (*TradeBoxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTradeBox",
			Handler:    _TradeBoxService_CreateTradeBox_Handler,
		},
		{
			MethodName: "DeleteTradeBox",
			Handler:    _TradeBoxService_DeleteTradeBox_Handler,
		},
		{
			MethodName: "CancelTradeBox",
			Handler:    _TradeBoxService_CancelTradeBox_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrackTradeBox",
			Handler:       _TradeBoxService_TrackTradeBox_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/timber/v1/trade_box.proto",
}
