// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/ikaros/v1/competition.proto

package ikaros

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	common "npln.nintendo.net/npln-practice/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchCreateCompetitionInvitationsRequest struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Parent        string                                `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Requests      []*CreateCompetitionInvitationRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateCompetitionInvitationsRequest) Reset() {
	*x = BatchCreateCompetitionInvitationsRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateCompetitionInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateCompetitionInvitationsRequest) ProtoMessage() {}

func (x *BatchCreateCompetitionInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateCompetitionInvitationsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateCompetitionInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{0}
}

func (x *BatchCreateCompetitionInvitationsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchCreateCompetitionInvitationsRequest) GetRequests() []*CreateCompetitionInvitationRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateCompetitionInvitationsResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	CompetitionInvitations []*CompetitionInvitation `protobuf:"bytes,1,rep,name=competition_invitations,json=competitionInvitations,proto3" json:"competition_invitations,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BatchCreateCompetitionInvitationsResponse) Reset() {
	*x = BatchCreateCompetitionInvitationsResponse{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateCompetitionInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateCompetitionInvitationsResponse) ProtoMessage() {}

func (x *BatchCreateCompetitionInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateCompetitionInvitationsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateCompetitionInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{1}
}

func (x *BatchCreateCompetitionInvitationsResponse) GetCompetitionInvitations() []*CompetitionInvitation {
	if x != nil {
		return x.CompetitionInvitations
	}
	return nil
}

type CreateCompetitionInvitationRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Parent                  string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	CompetitionInvitation   *CompetitionInvitation `protobuf:"bytes,2,opt,name=competition_invitation,json=competitionInvitation,proto3" json:"competition_invitation,omitempty"`
	CompetitionInvitationId string                 `protobuf:"bytes,3,opt,name=competition_invitation_id,json=competitionInvitationId,proto3" json:"competition_invitation_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CreateCompetitionInvitationRequest) Reset() {
	*x = CreateCompetitionInvitationRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompetitionInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompetitionInvitationRequest) ProtoMessage() {}

func (x *CreateCompetitionInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompetitionInvitationRequest.ProtoReflect.Descriptor instead.
func (*CreateCompetitionInvitationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCompetitionInvitationRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateCompetitionInvitationRequest) GetCompetitionInvitation() *CompetitionInvitation {
	if x != nil {
		return x.CompetitionInvitation
	}
	return nil
}

func (x *CreateCompetitionInvitationRequest) GetCompetitionInvitationId() string {
	if x != nil {
		return x.CompetitionInvitationId
	}
	return ""
}

type CreateCompetitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Competition   *Competition           `protobuf:"bytes,2,opt,name=competition,proto3" json:"competition,omitempty"`
	CompetitionId string                 `protobuf:"bytes,3,opt,name=competition_id,json=competitionId,proto3" json:"competition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompetitionRequest) Reset() {
	*x = CreateCompetitionRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompetitionRequest) ProtoMessage() {}

func (x *CreateCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompetitionRequest.ProtoReflect.Descriptor instead.
func (*CreateCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCompetitionRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateCompetitionRequest) GetCompetition() *Competition {
	if x != nil {
		return x.Competition
	}
	return nil
}

func (x *CreateCompetitionRequest) GetCompetitionId() string {
	if x != nil {
		return x.CompetitionId
	}
	return ""
}

type DeleteCompetitionInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompetitionInvitationRequest) Reset() {
	*x = DeleteCompetitionInvitationRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompetitionInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompetitionInvitationRequest) ProtoMessage() {}

func (x *DeleteCompetitionInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompetitionInvitationRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompetitionInvitationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCompetitionInvitationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteCompetitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompetitionRequest) Reset() {
	*x = DeleteCompetitionRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompetitionRequest) ProtoMessage() {}

func (x *DeleteCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompetitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCompetitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteCompetitionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type FinalizeCompetitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeCompetitionRequest) Reset() {
	*x = FinalizeCompetitionRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeCompetitionRequest) ProtoMessage() {}

func (x *FinalizeCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeCompetitionRequest.ProtoReflect.Descriptor instead.
func (*FinalizeCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{6}
}

func (x *FinalizeCompetitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FinalizeCompetitionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type GetCompetitionAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionAliasRequest) Reset() {
	*x = GetCompetitionAliasRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionAliasRequest) ProtoMessage() {}

func (x *GetCompetitionAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionAliasRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionAliasRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{7}
}

func (x *GetCompetitionAliasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCompetitionInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionInvitationRequest) Reset() {
	*x = GetCompetitionInvitationRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionInvitationRequest) ProtoMessage() {}

func (x *GetCompetitionInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionInvitationRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionInvitationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{8}
}

func (x *GetCompetitionInvitationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCompetitionNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionNotificationRequest) Reset() {
	*x = GetCompetitionNotificationRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionNotificationRequest) ProtoMessage() {}

func (x *GetCompetitionNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{9}
}

func (x *GetCompetitionNotificationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCompetitionParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionParticipantRequest) Reset() {
	*x = GetCompetitionParticipantRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionParticipantRequest) ProtoMessage() {}

func (x *GetCompetitionParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionParticipantRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionParticipantRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{10}
}

func (x *GetCompetitionParticipantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCompetitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	View          CompetitionView        `protobuf:"varint,2,opt,name=view,proto3,enum=nn.npln.ikaros.v1.CompetitionView" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionRequest) Reset() {
	*x = GetCompetitionRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionRequest) ProtoMessage() {}

func (x *GetCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{11}
}

func (x *GetCompetitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCompetitionRequest) GetView() CompetitionView {
	if x != nil {
		return x.View
	}
	return CompetitionView_COMPETITION_VIEW_UNSPECIFIED
}

type GetCompetitionUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitionUserRequest) Reset() {
	*x = GetCompetitionUserRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitionUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitionUserRequest) ProtoMessage() {}

func (x *GetCompetitionUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitionUserRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitionUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{12}
}

func (x *GetCompetitionUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCompetitionUserRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type ListCompetitionInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompetitionInvitationsRequest) Reset() {
	*x = ListCompetitionInvitationsRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompetitionInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompetitionInvitationsRequest) ProtoMessage() {}

func (x *ListCompetitionInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompetitionInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListCompetitionInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{13}
}

func (x *ListCompetitionInvitationsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListCompetitionInvitationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCompetitionInvitationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCompetitionInvitationsResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	CompetitionInvitations []*CompetitionInvitation `protobuf:"bytes,1,rep,name=competition_invitations,json=competitionInvitations,proto3" json:"competition_invitations,omitempty"`
	NextPageToken          string                   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListCompetitionInvitationsResponse) Reset() {
	*x = ListCompetitionInvitationsResponse{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompetitionInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompetitionInvitationsResponse) ProtoMessage() {}

func (x *ListCompetitionInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompetitionInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListCompetitionInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{14}
}

func (x *ListCompetitionInvitationsResponse) GetCompetitionInvitations() []*CompetitionInvitation {
	if x != nil {
		return x.CompetitionInvitations
	}
	return nil
}

func (x *ListCompetitionInvitationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SearchCompetitionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tenant           string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	PageSize         int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken        string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View             CompetitionView        `protobuf:"varint,4,opt,name=view,proto3,enum=nn.npln.ikaros.v1.CompetitionView" json:"view,omitempty"`
	CompetitionTypes []CompetitionType      `protobuf:"varint,6,rep,packed,name=competition_types,json=competitionTypes,proto3,enum=nn.npln.ikaros.v1.CompetitionType" json:"competition_types,omitempty"`
	QueryType        string                 `protobuf:"bytes,7,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	QueryParams      *common.MapValue       `protobuf:"bytes,8,opt,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchCompetitionsRequest) Reset() {
	*x = SearchCompetitionsRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCompetitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCompetitionsRequest) ProtoMessage() {}

func (x *SearchCompetitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCompetitionsRequest.ProtoReflect.Descriptor instead.
func (*SearchCompetitionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{15}
}

func (x *SearchCompetitionsRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *SearchCompetitionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchCompetitionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchCompetitionsRequest) GetView() CompetitionView {
	if x != nil {
		return x.View
	}
	return CompetitionView_COMPETITION_VIEW_UNSPECIFIED
}

func (x *SearchCompetitionsRequest) GetCompetitionTypes() []CompetitionType {
	if x != nil {
		return x.CompetitionTypes
	}
	return nil
}

func (x *SearchCompetitionsRequest) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *SearchCompetitionsRequest) GetQueryParams() *common.MapValue {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

type SearchCompetitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Competitions  []*Competition         `protobuf:"bytes,1,rep,name=competitions,proto3" json:"competitions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCompetitionsResponse) Reset() {
	*x = SearchCompetitionsResponse{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCompetitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCompetitionsResponse) ProtoMessage() {}

func (x *SearchCompetitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCompetitionsResponse.ProtoReflect.Descriptor instead.
func (*SearchCompetitionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{16}
}

func (x *SearchCompetitionsResponse) GetCompetitions() []*Competition {
	if x != nil {
		return x.Competitions
	}
	return nil
}

func (x *SearchCompetitionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateCompetitionNotificationRequest struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	CompetitionNotification *CompetitionNotification `protobuf:"bytes,1,opt,name=competition_notification,json=competitionNotification,proto3" json:"competition_notification,omitempty"`
	UpdateMask              *fieldmaskpb.FieldMask   `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateCompetitionNotificationRequest) Reset() {
	*x = UpdateCompetitionNotificationRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompetitionNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompetitionNotificationRequest) ProtoMessage() {}

func (x *UpdateCompetitionNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompetitionNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompetitionNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateCompetitionNotificationRequest) GetCompetitionNotification() *CompetitionNotification {
	if x != nil {
		return x.CompetitionNotification
	}
	return nil
}

func (x *UpdateCompetitionNotificationRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateCompetitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Competition   *Competition           `protobuf:"bytes,1,opt,name=competition,proto3" json:"competition,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompetitionRequest) Reset() {
	*x = UpdateCompetitionRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompetitionRequest) ProtoMessage() {}

func (x *UpdateCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompetitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateCompetitionRequest) GetCompetition() *Competition {
	if x != nil {
		return x.Competition
	}
	return nil
}

func (x *UpdateCompetitionRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateCompetitionUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompetitionUser *CompetitionUser       `protobuf:"bytes,1,opt,name=competition_user,json=competitionUser,proto3" json:"competition_user,omitempty"`
	UpdateMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateCompetitionUserRequest) Reset() {
	*x = UpdateCompetitionUserRequest{}
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompetitionUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompetitionUserRequest) ProtoMessage() {}

func (x *UpdateCompetitionUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_competition_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompetitionUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompetitionUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_competition_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateCompetitionUserRequest) GetCompetitionUser() *CompetitionUser {
	if x != nil {
		return x.CompetitionUser
	}
	return nil
}

func (x *UpdateCompetitionUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

var File_proto_ikaros_v1_competition_proto protoreflect.FileDescriptor

const file_proto_ikaros_v1_competition_proto_rawDesc = "" +
	"\n" +
	"!proto/ikaros/v1/competition.proto\x12\x11nn.npln.ikaros.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x18proto/common/value.proto\x1a\x1fproto/ikaros/v1/resources.proto\"\x95\x01\n" +
	"(BatchCreateCompetitionInvitationsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12Q\n" +
	"\brequests\x18\x02 \x03(\v25.nn.npln.ikaros.v1.CreateCompetitionInvitationRequestR\brequests\"\x8e\x01\n" +
	")BatchCreateCompetitionInvitationsResponse\x12a\n" +
	"\x17competition_invitations\x18\x01 \x03(\v2(.nn.npln.ikaros.v1.CompetitionInvitationR\x16competitionInvitations\"\xd9\x01\n" +
	"\"CreateCompetitionInvitationRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12_\n" +
	"\x16competition_invitation\x18\x02 \x01(\v2(.nn.npln.ikaros.v1.CompetitionInvitationR\x15competitionInvitation\x12:\n" +
	"\x19competition_invitation_id\x18\x03 \x01(\tR\x17competitionInvitationId\"\x9b\x01\n" +
	"\x18CreateCompetitionRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12@\n" +
	"\vcompetition\x18\x02 \x01(\v2\x1e.nn.npln.ikaros.v1.CompetitionR\vcompetition\x12%\n" +
	"\x0ecompetition_id\x18\x03 \x01(\tR\rcompetitionId\"8\n" +
	"\"DeleteCompetitionInvitationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x18DeleteCompetitionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"F\n" +
	"\x1aFinalizeCompetitionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"0\n" +
	"\x1aGetCompetitionAliasRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\x1fGetCompetitionInvitationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"!GetCompetitionNotificationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"6\n" +
	" GetCompetitionParticipantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"c\n" +
	"\x15GetCompetitionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\x04view\x18\x02 \x01(\x0e2\".nn.npln.ikaros.v1.CompetitionViewR\x04view\"h\n" +
	"\x19GetCompetitionUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"w\n" +
	"!ListCompetitionInvitationsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xaf\x01\n" +
	"\"ListCompetitionInvitationsResponse\x12a\n" +
	"\x17competition_invitations\x18\x01 \x03(\v2(.nn.npln.ikaros.v1.CompetitionInvitationR\x16competitionInvitations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd8\x02\n" +
	"\x19SearchCompetitionsRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x126\n" +
	"\x04view\x18\x04 \x01(\x0e2\".nn.npln.ikaros.v1.CompetitionViewR\x04view\x12S\n" +
	"\x11competition_types\x18\x06 \x03(\x0e2\".nn.npln.ikaros.v1.CompetitionTypeB\x02\x10\x01R\x10competitionTypes\x12\x1d\n" +
	"\n" +
	"query_type\x18\a \x01(\tR\tqueryType\x12;\n" +
	"\fquery_params\x18\b \x01(\v2\x18.nn.npln.common.MapValueR\vqueryParams\"\x88\x01\n" +
	"\x1aSearchCompetitionsResponse\x12B\n" +
	"\fcompetitions\x18\x01 \x03(\v2\x1e.nn.npln.ikaros.v1.CompetitionR\fcompetitions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xca\x01\n" +
	"$UpdateCompetitionNotificationRequest\x12e\n" +
	"\x18competition_notification\x18\x01 \x01(\v2*.nn.npln.ikaros.v1.CompetitionNotificationR\x17competitionNotification\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x99\x01\n" +
	"\x18UpdateCompetitionRequest\x12@\n" +
	"\vcompetition\x18\x01 \x01(\v2\x1e.nn.npln.ikaros.v1.CompetitionR\vcompetition\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\xaa\x01\n" +
	"\x1cUpdateCompetitionUserRequest\x12M\n" +
	"\x10competition_user\x18\x01 \x01(\v2\".nn.npln.ikaros.v1.CompetitionUserR\x0fcompetitionUser\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask2\xde\x0f\n" +
	"\x12CompetitionService\x12Z\n" +
	"\x0eGetCompetition\x12(.nn.npln.ikaros.v1.GetCompetitionRequest\x1a\x1e.nn.npln.ikaros.v1.Competition\x12`\n" +
	"\x11CreateCompetition\x12+.nn.npln.ikaros.v1.CreateCompetitionRequest\x1a\x1e.nn.npln.ikaros.v1.Competition\x12`\n" +
	"\x11UpdateCompetition\x12+.nn.npln.ikaros.v1.UpdateCompetitionRequest\x1a\x1e.nn.npln.ikaros.v1.Competition\x12X\n" +
	"\x11DeleteCompetition\x12+.nn.npln.ikaros.v1.DeleteCompetitionRequest\x1a\x16.google.protobuf.Empty\x12q\n" +
	"\x12SearchCompetitions\x12,.nn.npln.ikaros.v1.SearchCompetitionsRequest\x1a-.nn.npln.ikaros.v1.SearchCompetitionsResponse\x12i\n" +
	"\x13GetCompetitionAlias\x12-.nn.npln.ikaros.v1.GetCompetitionAliasRequest\x1a#.nn.npln.ikaros.v1.CompetitionAlias\x12x\n" +
	"\x18GetCompetitionInvitation\x122.nn.npln.ikaros.v1.GetCompetitionInvitationRequest\x1a(.nn.npln.ikaros.v1.CompetitionInvitation\x12~\n" +
	"\x1bCreateCompetitionInvitation\x125.nn.npln.ikaros.v1.CreateCompetitionInvitationRequest\x1a(.nn.npln.ikaros.v1.CompetitionInvitation\x12\x89\x01\n" +
	"\x1aListCompetitionInvitations\x124.nn.npln.ikaros.v1.ListCompetitionInvitationsRequest\x1a5.nn.npln.ikaros.v1.ListCompetitionInvitationsResponse\x12l\n" +
	"\x1bDeleteCompetitionInvitation\x125.nn.npln.ikaros.v1.DeleteCompetitionInvitationRequest\x1a\x16.google.protobuf.Empty\x12\x9e\x01\n" +
	"!BatchCreateCompetitionInvitations\x12;.nn.npln.ikaros.v1.BatchCreateCompetitionInvitationsRequest\x1a<.nn.npln.ikaros.v1.BatchCreateCompetitionInvitationsResponse\x12{\n" +
	"\x19GetCompetitionParticipant\x123.nn.npln.ikaros.v1.GetCompetitionParticipantRequest\x1a).nn.npln.ikaros.v1.CompetitionParticipant\x12\x80\x01\n" +
	"\x1cCreateCompetitionParticipant\x125.nn.npln.ikaros.v1.CreateCompetitionInvitationRequest\x1a).nn.npln.ikaros.v1.CompetitionParticipant\x12~\n" +
	"\x1aGetCompetitionNotification\x124.nn.npln.ikaros.v1.GetCompetitionNotificationRequest\x1a*.nn.npln.ikaros.v1.CompetitionNotification\x12\x84\x01\n" +
	"\x1dUpdateCompetitionNotification\x127.nn.npln.ikaros.v1.UpdateCompetitionNotificationRequest\x1a*.nn.npln.ikaros.v1.CompetitionNotification\x12f\n" +
	"\x12GetCompetitionUser\x12,.nn.npln.ikaros.v1.GetCompetitionUserRequest\x1a\".nn.npln.ikaros.v1.CompetitionUser\x12l\n" +
	"\x15UpdateCompetitionUser\x12/.nn.npln.ikaros.v1.UpdateCompetitionUserRequest\x1a\".nn.npln.ikaros.v1.CompetitionUserB8Z6npln.nintendo.net/npln-practice/proto/ikaros/v1;ikarosb\x06proto3"

var (
	file_proto_ikaros_v1_competition_proto_rawDescOnce sync.Once
	file_proto_ikaros_v1_competition_proto_rawDescData []byte
)

func file_proto_ikaros_v1_competition_proto_rawDescGZIP() []byte {
	file_proto_ikaros_v1_competition_proto_rawDescOnce.Do(func() {
		file_proto_ikaros_v1_competition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ikaros_v1_competition_proto_rawDesc), len(file_proto_ikaros_v1_competition_proto_rawDesc)))
	})
	return file_proto_ikaros_v1_competition_proto_rawDescData
}

var file_proto_ikaros_v1_competition_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_ikaros_v1_competition_proto_goTypes = []any{
	(*BatchCreateCompetitionInvitationsRequest)(nil),  // 0: nn.npln.ikaros.v1.BatchCreateCompetitionInvitationsRequest
	(*BatchCreateCompetitionInvitationsResponse)(nil), // 1: nn.npln.ikaros.v1.BatchCreateCompetitionInvitationsResponse
	(*CreateCompetitionInvitationRequest)(nil),        // 2: nn.npln.ikaros.v1.CreateCompetitionInvitationRequest
	(*CreateCompetitionRequest)(nil),                  // 3: nn.npln.ikaros.v1.CreateCompetitionRequest
	(*DeleteCompetitionInvitationRequest)(nil),        // 4: nn.npln.ikaros.v1.DeleteCompetitionInvitationRequest
	(*DeleteCompetitionRequest)(nil),                  // 5: nn.npln.ikaros.v1.DeleteCompetitionRequest
	(*FinalizeCompetitionRequest)(nil),                // 6: nn.npln.ikaros.v1.FinalizeCompetitionRequest
	(*GetCompetitionAliasRequest)(nil),                // 7: nn.npln.ikaros.v1.GetCompetitionAliasRequest
	(*GetCompetitionInvitationRequest)(nil),           // 8: nn.npln.ikaros.v1.GetCompetitionInvitationRequest
	(*GetCompetitionNotificationRequest)(nil),         // 9: nn.npln.ikaros.v1.GetCompetitionNotificationRequest
	(*GetCompetitionParticipantRequest)(nil),          // 10: nn.npln.ikaros.v1.GetCompetitionParticipantRequest
	(*GetCompetitionRequest)(nil),                     // 11: nn.npln.ikaros.v1.GetCompetitionRequest
	(*GetCompetitionUserRequest)(nil),                 // 12: nn.npln.ikaros.v1.GetCompetitionUserRequest
	(*ListCompetitionInvitationsRequest)(nil),         // 13: nn.npln.ikaros.v1.ListCompetitionInvitationsRequest
	(*ListCompetitionInvitationsResponse)(nil),        // 14: nn.npln.ikaros.v1.ListCompetitionInvitationsResponse
	(*SearchCompetitionsRequest)(nil),                 // 15: nn.npln.ikaros.v1.SearchCompetitionsRequest
	(*SearchCompetitionsResponse)(nil),                // 16: nn.npln.ikaros.v1.SearchCompetitionsResponse
	(*UpdateCompetitionNotificationRequest)(nil),      // 17: nn.npln.ikaros.v1.UpdateCompetitionNotificationRequest
	(*UpdateCompetitionRequest)(nil),                  // 18: nn.npln.ikaros.v1.UpdateCompetitionRequest
	(*UpdateCompetitionUserRequest)(nil),              // 19: nn.npln.ikaros.v1.UpdateCompetitionUserRequest
	(*CompetitionInvitation)(nil),                     // 20: nn.npln.ikaros.v1.CompetitionInvitation
	(*Competition)(nil),                               // 21: nn.npln.ikaros.v1.Competition
	(CompetitionView)(0),                              // 22: nn.npln.ikaros.v1.CompetitionView
	(*fieldmaskpb.FieldMask)(nil),                     // 23: google.protobuf.FieldMask
	(CompetitionType)(0),                              // 24: nn.npln.ikaros.v1.CompetitionType
	(*common.MapValue)(nil),                           // 25: nn.npln.common.MapValue
	(*CompetitionNotification)(nil),                   // 26: nn.npln.ikaros.v1.CompetitionNotification
	(*CompetitionUser)(nil),                           // 27: nn.npln.ikaros.v1.CompetitionUser
	(*emptypb.Empty)(nil),                             // 28: google.protobuf.Empty
	(*CompetitionAlias)(nil),                          // 29: nn.npln.ikaros.v1.CompetitionAlias
	(*CompetitionParticipant)(nil),                    // 30: nn.npln.ikaros.v1.CompetitionParticipant
}
var file_proto_ikaros_v1_competition_proto_depIdxs = []int32{
	2,  // 0: nn.npln.ikaros.v1.BatchCreateCompetitionInvitationsRequest.requests:type_name -> nn.npln.ikaros.v1.CreateCompetitionInvitationRequest
	20, // 1: nn.npln.ikaros.v1.BatchCreateCompetitionInvitationsResponse.competition_invitations:type_name -> nn.npln.ikaros.v1.CompetitionInvitation
	20, // 2: nn.npln.ikaros.v1.CreateCompetitionInvitationRequest.competition_invitation:type_name -> nn.npln.ikaros.v1.CompetitionInvitation
	21, // 3: nn.npln.ikaros.v1.CreateCompetitionRequest.competition:type_name -> nn.npln.ikaros.v1.Competition
	22, // 4: nn.npln.ikaros.v1.GetCompetitionRequest.view:type_name -> nn.npln.ikaros.v1.CompetitionView
	23, // 5: nn.npln.ikaros.v1.GetCompetitionUserRequest.read_mask:type_name -> google.protobuf.FieldMask
	20, // 6: nn.npln.ikaros.v1.ListCompetitionInvitationsResponse.competition_invitations:type_name -> nn.npln.ikaros.v1.CompetitionInvitation
	22, // 7: nn.npln.ikaros.v1.SearchCompetitionsRequest.view:type_name -> nn.npln.ikaros.v1.CompetitionView
	24, // 8: nn.npln.ikaros.v1.SearchCompetitionsRequest.competition_types:type_name -> nn.npln.ikaros.v1.CompetitionType
	25, // 9: nn.npln.ikaros.v1.SearchCompetitionsRequest.query_params:type_name -> nn.npln.common.MapValue
	21, // 10: nn.npln.ikaros.v1.SearchCompetitionsResponse.competitions:type_name -> nn.npln.ikaros.v1.Competition
	26, // 11: nn.npln.ikaros.v1.UpdateCompetitionNotificationRequest.competition_notification:type_name -> nn.npln.ikaros.v1.CompetitionNotification
	23, // 12: nn.npln.ikaros.v1.UpdateCompetitionNotificationRequest.update_mask:type_name -> google.protobuf.FieldMask
	21, // 13: nn.npln.ikaros.v1.UpdateCompetitionRequest.competition:type_name -> nn.npln.ikaros.v1.Competition
	23, // 14: nn.npln.ikaros.v1.UpdateCompetitionRequest.update_mask:type_name -> google.protobuf.FieldMask
	27, // 15: nn.npln.ikaros.v1.UpdateCompetitionUserRequest.competition_user:type_name -> nn.npln.ikaros.v1.CompetitionUser
	23, // 16: nn.npln.ikaros.v1.UpdateCompetitionUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	11, // 17: nn.npln.ikaros.v1.CompetitionService.GetCompetition:input_type -> nn.npln.ikaros.v1.GetCompetitionRequest
	3,  // 18: nn.npln.ikaros.v1.CompetitionService.CreateCompetition:input_type -> nn.npln.ikaros.v1.CreateCompetitionRequest
	18, // 19: nn.npln.ikaros.v1.CompetitionService.UpdateCompetition:input_type -> nn.npln.ikaros.v1.UpdateCompetitionRequest
	5,  // 20: nn.npln.ikaros.v1.CompetitionService.DeleteCompetition:input_type -> nn.npln.ikaros.v1.DeleteCompetitionRequest
	15, // 21: nn.npln.ikaros.v1.CompetitionService.SearchCompetitions:input_type -> nn.npln.ikaros.v1.SearchCompetitionsRequest
	7,  // 22: nn.npln.ikaros.v1.CompetitionService.GetCompetitionAlias:input_type -> nn.npln.ikaros.v1.GetCompetitionAliasRequest
	8,  // 23: nn.npln.ikaros.v1.CompetitionService.GetCompetitionInvitation:input_type -> nn.npln.ikaros.v1.GetCompetitionInvitationRequest
	2,  // 24: nn.npln.ikaros.v1.CompetitionService.CreateCompetitionInvitation:input_type -> nn.npln.ikaros.v1.CreateCompetitionInvitationRequest
	13, // 25: nn.npln.ikaros.v1.CompetitionService.ListCompetitionInvitations:input_type -> nn.npln.ikaros.v1.ListCompetitionInvitationsRequest
	4,  // 26: nn.npln.ikaros.v1.CompetitionService.DeleteCompetitionInvitation:input_type -> nn.npln.ikaros.v1.DeleteCompetitionInvitationRequest
	0,  // 27: nn.npln.ikaros.v1.CompetitionService.BatchCreateCompetitionInvitations:input_type -> nn.npln.ikaros.v1.BatchCreateCompetitionInvitationsRequest
	10, // 28: nn.npln.ikaros.v1.CompetitionService.GetCompetitionParticipant:input_type -> nn.npln.ikaros.v1.GetCompetitionParticipantRequest
	2,  // 29: nn.npln.ikaros.v1.CompetitionService.CreateCompetitionParticipant:input_type -> nn.npln.ikaros.v1.CreateCompetitionInvitationRequest
	9,  // 30: nn.npln.ikaros.v1.CompetitionService.GetCompetitionNotification:input_type -> nn.npln.ikaros.v1.GetCompetitionNotificationRequest
	17, // 31: nn.npln.ikaros.v1.CompetitionService.UpdateCompetitionNotification:input_type -> nn.npln.ikaros.v1.UpdateCompetitionNotificationRequest
	12, // 32: nn.npln.ikaros.v1.CompetitionService.GetCompetitionUser:input_type -> nn.npln.ikaros.v1.GetCompetitionUserRequest
	19, // 33: nn.npln.ikaros.v1.CompetitionService.UpdateCompetitionUser:input_type -> nn.npln.ikaros.v1.UpdateCompetitionUserRequest
	21, // 34: nn.npln.ikaros.v1.CompetitionService.GetCompetition:output_type -> nn.npln.ikaros.v1.Competition
	21, // 35: nn.npln.ikaros.v1.CompetitionService.CreateCompetition:output_type -> nn.npln.ikaros.v1.Competition
	21, // 36: nn.npln.ikaros.v1.CompetitionService.UpdateCompetition:output_type -> nn.npln.ikaros.v1.Competition
	28, // 37: nn.npln.ikaros.v1.CompetitionService.DeleteCompetition:output_type -> google.protobuf.Empty
	16, // 38: nn.npln.ikaros.v1.CompetitionService.SearchCompetitions:output_type -> nn.npln.ikaros.v1.SearchCompetitionsResponse
	29, // 39: nn.npln.ikaros.v1.CompetitionService.GetCompetitionAlias:output_type -> nn.npln.ikaros.v1.CompetitionAlias
	20, // 40: nn.npln.ikaros.v1.CompetitionService.GetCompetitionInvitation:output_type -> nn.npln.ikaros.v1.CompetitionInvitation
	20, // 41: nn.npln.ikaros.v1.CompetitionService.CreateCompetitionInvitation:output_type -> nn.npln.ikaros.v1.CompetitionInvitation
	14, // 42: nn.npln.ikaros.v1.CompetitionService.ListCompetitionInvitations:output_type -> nn.npln.ikaros.v1.ListCompetitionInvitationsResponse
	28, // 43: nn.npln.ikaros.v1.CompetitionService.DeleteCompetitionInvitation:output_type -> google.protobuf.Empty
	1,  // 44: nn.npln.ikaros.v1.CompetitionService.BatchCreateCompetitionInvitations:output_type -> nn.npln.ikaros.v1.BatchCreateCompetitionInvitationsResponse
	30, // 45: nn.npln.ikaros.v1.CompetitionService.GetCompetitionParticipant:output_type -> nn.npln.ikaros.v1.CompetitionParticipant
	30, // 46: nn.npln.ikaros.v1.CompetitionService.CreateCompetitionParticipant:output_type -> nn.npln.ikaros.v1.CompetitionParticipant
	26, // 47: nn.npln.ikaros.v1.CompetitionService.GetCompetitionNotification:output_type -> nn.npln.ikaros.v1.CompetitionNotification
	26, // 48: nn.npln.ikaros.v1.CompetitionService.UpdateCompetitionNotification:output_type -> nn.npln.ikaros.v1.CompetitionNotification
	27, // 49: nn.npln.ikaros.v1.CompetitionService.GetCompetitionUser:output_type -> nn.npln.ikaros.v1.CompetitionUser
	27, // 50: nn.npln.ikaros.v1.CompetitionService.UpdateCompetitionUser:output_type -> nn.npln.ikaros.v1.CompetitionUser
	34, // [34:51] is the sub-list for method output_type
	17, // [17:34] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_ikaros_v1_competition_proto_init() }
func file_proto_ikaros_v1_competition_proto_init() {
	if File_proto_ikaros_v1_competition_proto != nil {
		return
	}
	file_proto_ikaros_v1_resources_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ikaros_v1_competition_proto_rawDesc), len(file_proto_ikaros_v1_competition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ikaros_v1_competition_proto_goTypes,
		DependencyIndexes: file_proto_ikaros_v1_competition_proto_depIdxs,
		MessageInfos:      file_proto_ikaros_v1_competition_proto_msgTypes,
	}.Build()
	File_proto_ikaros_v1_competition_proto = out.File
	file_proto_ikaros_v1_competition_proto_goTypes = nil
	file_proto_ikaros_v1_competition_proto_depIdxs = nil
}
