// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/ikaros/v1/competition.proto

package ikaros

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompetitionService_GetCompetition_FullMethodName                    = "/nn.npln.ikaros.v1.CompetitionService/GetCompetition"
	CompetitionService_CreateCompetition_FullMethodName                 = "/nn.npln.ikaros.v1.CompetitionService/CreateCompetition"
	CompetitionService_UpdateCompetition_FullMethodName                 = "/nn.npln.ikaros.v1.CompetitionService/UpdateCompetition"
	CompetitionService_DeleteCompetition_FullMethodName                 = "/nn.npln.ikaros.v1.CompetitionService/DeleteCompetition"
	CompetitionService_SearchCompetitions_FullMethodName                = "/nn.npln.ikaros.v1.CompetitionService/SearchCompetitions"
	CompetitionService_GetCompetitionAlias_FullMethodName               = "/nn.npln.ikaros.v1.CompetitionService/GetCompetitionAlias"
	CompetitionService_GetCompetitionInvitation_FullMethodName          = "/nn.npln.ikaros.v1.CompetitionService/GetCompetitionInvitation"
	CompetitionService_CreateCompetitionInvitation_FullMethodName       = "/nn.npln.ikaros.v1.CompetitionService/CreateCompetitionInvitation"
	CompetitionService_ListCompetitionInvitations_FullMethodName        = "/nn.npln.ikaros.v1.CompetitionService/ListCompetitionInvitations"
	CompetitionService_DeleteCompetitionInvitation_FullMethodName       = "/nn.npln.ikaros.v1.CompetitionService/DeleteCompetitionInvitation"
	CompetitionService_BatchCreateCompetitionInvitations_FullMethodName = "/nn.npln.ikaros.v1.CompetitionService/BatchCreateCompetitionInvitations"
	CompetitionService_GetCompetitionParticipant_FullMethodName         = "/nn.npln.ikaros.v1.CompetitionService/GetCompetitionParticipant"
	CompetitionService_CreateCompetitionParticipant_FullMethodName      = "/nn.npln.ikaros.v1.CompetitionService/CreateCompetitionParticipant"
	CompetitionService_GetCompetitionNotification_FullMethodName        = "/nn.npln.ikaros.v1.CompetitionService/GetCompetitionNotification"
	CompetitionService_UpdateCompetitionNotification_FullMethodName     = "/nn.npln.ikaros.v1.CompetitionService/UpdateCompetitionNotification"
	CompetitionService_GetCompetitionUser_FullMethodName                = "/nn.npln.ikaros.v1.CompetitionService/GetCompetitionUser"
	CompetitionService_UpdateCompetitionUser_FullMethodName             = "/nn.npln.ikaros.v1.CompetitionService/UpdateCompetitionUser"
)

// CompetitionServiceClient is the client API for CompetitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompetitionServiceClient interface {
	GetCompetition(ctx context.Context, in *GetCompetitionRequest, opts ...grpc.CallOption) (*Competition, error)
	CreateCompetition(ctx context.Context, in *CreateCompetitionRequest, opts ...grpc.CallOption) (*Competition, error)
	UpdateCompetition(ctx context.Context, in *UpdateCompetitionRequest, opts ...grpc.CallOption) (*Competition, error)
	DeleteCompetition(ctx context.Context, in *DeleteCompetitionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SearchCompetitions(ctx context.Context, in *SearchCompetitionsRequest, opts ...grpc.CallOption) (*SearchCompetitionsResponse, error)
	// rpc HostCompetition(?) returns (?)
	// rpc FinalizeCompetition(FinalizeCompetitionRequest) returns (?);
	GetCompetitionAlias(ctx context.Context, in *GetCompetitionAliasRequest, opts ...grpc.CallOption) (*CompetitionAlias, error)
	GetCompetitionInvitation(ctx context.Context, in *GetCompetitionInvitationRequest, opts ...grpc.CallOption) (*CompetitionInvitation, error)
	CreateCompetitionInvitation(ctx context.Context, in *CreateCompetitionInvitationRequest, opts ...grpc.CallOption) (*CompetitionInvitation, error)
	ListCompetitionInvitations(ctx context.Context, in *ListCompetitionInvitationsRequest, opts ...grpc.CallOption) (*ListCompetitionInvitationsResponse, error)
	DeleteCompetitionInvitation(ctx context.Context, in *DeleteCompetitionInvitationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BatchCreateCompetitionInvitations(ctx context.Context, in *BatchCreateCompetitionInvitationsRequest, opts ...grpc.CallOption) (*BatchCreateCompetitionInvitationsResponse, error)
	GetCompetitionParticipant(ctx context.Context, in *GetCompetitionParticipantRequest, opts ...grpc.CallOption) (*CompetitionParticipant, error)
	CreateCompetitionParticipant(ctx context.Context, in *CreateCompetitionInvitationRequest, opts ...grpc.CallOption) (*CompetitionParticipant, error)
	// rpc ActivateCompetitionParticipant(?) returns (?)
	// rpc DeactivateCompetitionParticipant(?) returns (?)
	// rpc CancelCompetitionParticipant(?) returns (?)
	GetCompetitionNotification(ctx context.Context, in *GetCompetitionNotificationRequest, opts ...grpc.CallOption) (*CompetitionNotification, error)
	UpdateCompetitionNotification(ctx context.Context, in *UpdateCompetitionNotificationRequest, opts ...grpc.CallOption) (*CompetitionNotification, error)
	// rpc ReceiveCompetitionNtoification(?) returns (?)
	// rpc InvalidateCompetitionNotification(?) returns (?)
	GetCompetitionUser(ctx context.Context, in *GetCompetitionUserRequest, opts ...grpc.CallOption) (*CompetitionUser, error)
	// rpc CreateCompetitionUser(?) returns (?)
	UpdateCompetitionUser(ctx context.Context, in *UpdateCompetitionUserRequest, opts ...grpc.CallOption) (*CompetitionUser, error)
}

type competitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompetitionServiceClient(cc grpc.ClientConnInterface) CompetitionServiceClient {
	return &competitionServiceClient{cc}
}

func (c *competitionServiceClient) GetCompetition(ctx context.Context, in *GetCompetitionRequest, opts ...grpc.CallOption) (*Competition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Competition)
	err := c.cc.Invoke(ctx, CompetitionService_GetCompetition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) CreateCompetition(ctx context.Context, in *CreateCompetitionRequest, opts ...grpc.CallOption) (*Competition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Competition)
	err := c.cc.Invoke(ctx, CompetitionService_CreateCompetition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) UpdateCompetition(ctx context.Context, in *UpdateCompetitionRequest, opts ...grpc.CallOption) (*Competition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Competition)
	err := c.cc.Invoke(ctx, CompetitionService_UpdateCompetition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) DeleteCompetition(ctx context.Context, in *DeleteCompetitionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CompetitionService_DeleteCompetition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) SearchCompetitions(ctx context.Context, in *SearchCompetitionsRequest, opts ...grpc.CallOption) (*SearchCompetitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCompetitionsResponse)
	err := c.cc.Invoke(ctx, CompetitionService_SearchCompetitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) GetCompetitionAlias(ctx context.Context, in *GetCompetitionAliasRequest, opts ...grpc.CallOption) (*CompetitionAlias, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompetitionAlias)
	err := c.cc.Invoke(ctx, CompetitionService_GetCompetitionAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) GetCompetitionInvitation(ctx context.Context, in *GetCompetitionInvitationRequest, opts ...grpc.CallOption) (*CompetitionInvitation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompetitionInvitation)
	err := c.cc.Invoke(ctx, CompetitionService_GetCompetitionInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) CreateCompetitionInvitation(ctx context.Context, in *CreateCompetitionInvitationRequest, opts ...grpc.CallOption) (*CompetitionInvitation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompetitionInvitation)
	err := c.cc.Invoke(ctx, CompetitionService_CreateCompetitionInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) ListCompetitionInvitations(ctx context.Context, in *ListCompetitionInvitationsRequest, opts ...grpc.CallOption) (*ListCompetitionInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCompetitionInvitationsResponse)
	err := c.cc.Invoke(ctx, CompetitionService_ListCompetitionInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) DeleteCompetitionInvitation(ctx context.Context, in *DeleteCompetitionInvitationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CompetitionService_DeleteCompetitionInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) BatchCreateCompetitionInvitations(ctx context.Context, in *BatchCreateCompetitionInvitationsRequest, opts ...grpc.CallOption) (*BatchCreateCompetitionInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateCompetitionInvitationsResponse)
	err := c.cc.Invoke(ctx, CompetitionService_BatchCreateCompetitionInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) GetCompetitionParticipant(ctx context.Context, in *GetCompetitionParticipantRequest, opts ...grpc.CallOption) (*CompetitionParticipant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompetitionParticipant)
	err := c.cc.Invoke(ctx, CompetitionService_GetCompetitionParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) CreateCompetitionParticipant(ctx context.Context, in *CreateCompetitionInvitationRequest, opts ...grpc.CallOption) (*CompetitionParticipant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompetitionParticipant)
	err := c.cc.Invoke(ctx, CompetitionService_CreateCompetitionParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) GetCompetitionNotification(ctx context.Context, in *GetCompetitionNotificationRequest, opts ...grpc.CallOption) (*CompetitionNotification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompetitionNotification)
	err := c.cc.Invoke(ctx, CompetitionService_GetCompetitionNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) UpdateCompetitionNotification(ctx context.Context, in *UpdateCompetitionNotificationRequest, opts ...grpc.CallOption) (*CompetitionNotification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompetitionNotification)
	err := c.cc.Invoke(ctx, CompetitionService_UpdateCompetitionNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) GetCompetitionUser(ctx context.Context, in *GetCompetitionUserRequest, opts ...grpc.CallOption) (*CompetitionUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompetitionUser)
	err := c.cc.Invoke(ctx, CompetitionService_GetCompetitionUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) UpdateCompetitionUser(ctx context.Context, in *UpdateCompetitionUserRequest, opts ...grpc.CallOption) (*CompetitionUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompetitionUser)
	err := c.cc.Invoke(ctx, CompetitionService_UpdateCompetitionUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompetitionServiceServer is the server API for CompetitionService service.
// All implementations must embed UnimplementedCompetitionServiceServer
// for forward compatibility.
type CompetitionServiceServer interface {
	GetCompetition(context.Context, *GetCompetitionRequest) (*Competition, error)
	CreateCompetition(context.Context, *CreateCompetitionRequest) (*Competition, error)
	UpdateCompetition(context.Context, *UpdateCompetitionRequest) (*Competition, error)
	DeleteCompetition(context.Context, *DeleteCompetitionRequest) (*emptypb.Empty, error)
	SearchCompetitions(context.Context, *SearchCompetitionsRequest) (*SearchCompetitionsResponse, error)
	// rpc HostCompetition(?) returns (?)
	// rpc FinalizeCompetition(FinalizeCompetitionRequest) returns (?);
	GetCompetitionAlias(context.Context, *GetCompetitionAliasRequest) (*CompetitionAlias, error)
	GetCompetitionInvitation(context.Context, *GetCompetitionInvitationRequest) (*CompetitionInvitation, error)
	CreateCompetitionInvitation(context.Context, *CreateCompetitionInvitationRequest) (*CompetitionInvitation, error)
	ListCompetitionInvitations(context.Context, *ListCompetitionInvitationsRequest) (*ListCompetitionInvitationsResponse, error)
	DeleteCompetitionInvitation(context.Context, *DeleteCompetitionInvitationRequest) (*emptypb.Empty, error)
	BatchCreateCompetitionInvitations(context.Context, *BatchCreateCompetitionInvitationsRequest) (*BatchCreateCompetitionInvitationsResponse, error)
	GetCompetitionParticipant(context.Context, *GetCompetitionParticipantRequest) (*CompetitionParticipant, error)
	CreateCompetitionParticipant(context.Context, *CreateCompetitionInvitationRequest) (*CompetitionParticipant, error)
	// rpc ActivateCompetitionParticipant(?) returns (?)
	// rpc DeactivateCompetitionParticipant(?) returns (?)
	// rpc CancelCompetitionParticipant(?) returns (?)
	GetCompetitionNotification(context.Context, *GetCompetitionNotificationRequest) (*CompetitionNotification, error)
	UpdateCompetitionNotification(context.Context, *UpdateCompetitionNotificationRequest) (*CompetitionNotification, error)
	// rpc ReceiveCompetitionNtoification(?) returns (?)
	// rpc InvalidateCompetitionNotification(?) returns (?)
	GetCompetitionUser(context.Context, *GetCompetitionUserRequest) (*CompetitionUser, error)
	// rpc CreateCompetitionUser(?) returns (?)
	UpdateCompetitionUser(context.Context, *UpdateCompetitionUserRequest) (*CompetitionUser, error)
	mustEmbedUnimplementedCompetitionServiceServer()
}

// UnimplementedCompetitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompetitionServiceServer struct{}

func (UnimplementedCompetitionServiceServer) GetCompetition(context.Context, *GetCompetitionRequest) (*Competition, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompetition not implemented")
}
func (UnimplementedCompetitionServiceServer) CreateCompetition(context.Context, *CreateCompetitionRequest) (*Competition, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCompetition not implemented")
}
func (UnimplementedCompetitionServiceServer) UpdateCompetition(context.Context, *UpdateCompetitionRequest) (*Competition, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCompetition not implemented")
}
func (UnimplementedCompetitionServiceServer) DeleteCompetition(context.Context, *DeleteCompetitionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCompetition not implemented")
}
func (UnimplementedCompetitionServiceServer) SearchCompetitions(context.Context, *SearchCompetitionsRequest) (*SearchCompetitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchCompetitions not implemented")
}
func (UnimplementedCompetitionServiceServer) GetCompetitionAlias(context.Context, *GetCompetitionAliasRequest) (*CompetitionAlias, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompetitionAlias not implemented")
}
func (UnimplementedCompetitionServiceServer) GetCompetitionInvitation(context.Context, *GetCompetitionInvitationRequest) (*CompetitionInvitation, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompetitionInvitation not implemented")
}
func (UnimplementedCompetitionServiceServer) CreateCompetitionInvitation(context.Context, *CreateCompetitionInvitationRequest) (*CompetitionInvitation, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCompetitionInvitation not implemented")
}
func (UnimplementedCompetitionServiceServer) ListCompetitionInvitations(context.Context, *ListCompetitionInvitationsRequest) (*ListCompetitionInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCompetitionInvitations not implemented")
}
func (UnimplementedCompetitionServiceServer) DeleteCompetitionInvitation(context.Context, *DeleteCompetitionInvitationRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCompetitionInvitation not implemented")
}
func (UnimplementedCompetitionServiceServer) BatchCreateCompetitionInvitations(context.Context, *BatchCreateCompetitionInvitationsRequest) (*BatchCreateCompetitionInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateCompetitionInvitations not implemented")
}
func (UnimplementedCompetitionServiceServer) GetCompetitionParticipant(context.Context, *GetCompetitionParticipantRequest) (*CompetitionParticipant, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompetitionParticipant not implemented")
}
func (UnimplementedCompetitionServiceServer) CreateCompetitionParticipant(context.Context, *CreateCompetitionInvitationRequest) (*CompetitionParticipant, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCompetitionParticipant not implemented")
}
func (UnimplementedCompetitionServiceServer) GetCompetitionNotification(context.Context, *GetCompetitionNotificationRequest) (*CompetitionNotification, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompetitionNotification not implemented")
}
func (UnimplementedCompetitionServiceServer) UpdateCompetitionNotification(context.Context, *UpdateCompetitionNotificationRequest) (*CompetitionNotification, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCompetitionNotification not implemented")
}
func (UnimplementedCompetitionServiceServer) GetCompetitionUser(context.Context, *GetCompetitionUserRequest) (*CompetitionUser, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompetitionUser not implemented")
}
func (UnimplementedCompetitionServiceServer) UpdateCompetitionUser(context.Context, *UpdateCompetitionUserRequest) (*CompetitionUser, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCompetitionUser not implemented")
}
func (UnimplementedCompetitionServiceServer) mustEmbedUnimplementedCompetitionServiceServer() {}
func (UnimplementedCompetitionServiceServer) testEmbeddedByValue()                            {}

// UnsafeCompetitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompetitionServiceServer will
// result in compilation errors.
type UnsafeCompetitionServiceServer interface {
	mustEmbedUnimplementedCompetitionServiceServer()
}

func RegisterCompetitionServiceServer(s grpc.ServiceRegistrar, srv CompetitionServiceServer) {
	// If the following call panics, it indicates UnimplementedCompetitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompetitionService_ServiceDesc, srv)
}

func _CompetitionService_GetCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).GetCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_GetCompetition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).GetCompetition(ctx, req.(*GetCompetitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_CreateCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompetitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).CreateCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_CreateCompetition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).CreateCompetition(ctx, req.(*CreateCompetitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_UpdateCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompetitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).UpdateCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_UpdateCompetition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).UpdateCompetition(ctx, req.(*UpdateCompetitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_DeleteCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCompetitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).DeleteCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_DeleteCompetition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).DeleteCompetition(ctx, req.(*DeleteCompetitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_SearchCompetitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCompetitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).SearchCompetitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_SearchCompetitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).SearchCompetitions(ctx, req.(*SearchCompetitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_GetCompetitionAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).GetCompetitionAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_GetCompetitionAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).GetCompetitionAlias(ctx, req.(*GetCompetitionAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_GetCompetitionInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).GetCompetitionInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_GetCompetitionInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).GetCompetitionInvitation(ctx, req.(*GetCompetitionInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_CreateCompetitionInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompetitionInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).CreateCompetitionInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_CreateCompetitionInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).CreateCompetitionInvitation(ctx, req.(*CreateCompetitionInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_ListCompetitionInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCompetitionInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).ListCompetitionInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_ListCompetitionInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).ListCompetitionInvitations(ctx, req.(*ListCompetitionInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_DeleteCompetitionInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCompetitionInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).DeleteCompetitionInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_DeleteCompetitionInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).DeleteCompetitionInvitation(ctx, req.(*DeleteCompetitionInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_BatchCreateCompetitionInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateCompetitionInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).BatchCreateCompetitionInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_BatchCreateCompetitionInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).BatchCreateCompetitionInvitations(ctx, req.(*BatchCreateCompetitionInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_GetCompetitionParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).GetCompetitionParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_GetCompetitionParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).GetCompetitionParticipant(ctx, req.(*GetCompetitionParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_CreateCompetitionParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompetitionInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).CreateCompetitionParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_CreateCompetitionParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).CreateCompetitionParticipant(ctx, req.(*CreateCompetitionInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_GetCompetitionNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).GetCompetitionNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_GetCompetitionNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).GetCompetitionNotification(ctx, req.(*GetCompetitionNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_UpdateCompetitionNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompetitionNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).UpdateCompetitionNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_UpdateCompetitionNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).UpdateCompetitionNotification(ctx, req.(*UpdateCompetitionNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_GetCompetitionUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).GetCompetitionUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_GetCompetitionUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).GetCompetitionUser(ctx, req.(*GetCompetitionUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_UpdateCompetitionUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompetitionUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).UpdateCompetitionUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitionService_UpdateCompetitionUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).UpdateCompetitionUser(ctx, req.(*UpdateCompetitionUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompetitionService_ServiceDesc is the grpc.ServiceDesc for CompetitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompetitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nn.npln.ikaros.v1.CompetitionService",
	HandlerType: (*CompetitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCompetition",
			Handler:    _CompetitionService_GetCompetition_Handler,
		},
		{
			MethodName: "CreateCompetition",
			Handler:    _CompetitionService_CreateCompetition_Handler,
		},
		{
			MethodName: "UpdateCompetition",
			Handler:    _CompetitionService_UpdateCompetition_Handler,
		},
		{
			MethodName: "DeleteCompetition",
			Handler:    _CompetitionService_DeleteCompetition_Handler,
		},
		{
			MethodName: "SearchCompetitions",
			Handler:    _CompetitionService_SearchCompetitions_Handler,
		},
		{
			MethodName: "GetCompetitionAlias",
			Handler:    _CompetitionService_GetCompetitionAlias_Handler,
		},
		{
			MethodName: "GetCompetitionInvitation",
			Handler:    _CompetitionService_GetCompetitionInvitation_Handler,
		},
		{
			MethodName: "CreateCompetitionInvitation",
			Handler:    _CompetitionService_CreateCompetitionInvitation_Handler,
		},
		{
			MethodName: "ListCompetitionInvitations",
			Handler:    _CompetitionService_ListCompetitionInvitations_Handler,
		},
		{
			MethodName: "DeleteCompetitionInvitation",
			Handler:    _CompetitionService_DeleteCompetitionInvitation_Handler,
		},
		{
			MethodName: "BatchCreateCompetitionInvitations",
			Handler:    _CompetitionService_BatchCreateCompetitionInvitations_Handler,
		},
		{
			MethodName: "GetCompetitionParticipant",
			Handler:    _CompetitionService_GetCompetitionParticipant_Handler,
		},
		{
			MethodName: "CreateCompetitionParticipant",
			Handler:    _CompetitionService_CreateCompetitionParticipant_Handler,
		},
		{
			MethodName: "GetCompetitionNotification",
			Handler:    _CompetitionService_GetCompetitionNotification_Handler,
		},
		{
			MethodName: "UpdateCompetitionNotification",
			Handler:    _CompetitionService_UpdateCompetitionNotification_Handler,
		},
		{
			MethodName: "GetCompetitionUser",
			Handler:    _CompetitionService_GetCompetitionUser_Handler,
		},
		{
			MethodName: "UpdateCompetitionUser",
			Handler:    _CompetitionService_UpdateCompetitionUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ikaros/v1/competition.proto",
}
