// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/ikaros/v1/resources.proto

package ikaros

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	common "npln.nintendo.net/npln-practice/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattleBehavior int32

const (
	BattleBehavior_BATTLE_BEHAVIOR_UNSPECIFIED       BattleBehavior = 0
	BattleBehavior_BEHAVIOR_SUCCESSFUL               BattleBehavior = 0
	BattleBehavior_BEHAVIOR_DISCONNECTED             BattleBehavior = 1
	BattleBehavior_BEHAVIOR_CHEATED                  BattleBehavior = 2
	BattleBehavior_BEHAVIOR_DISCONNECTED_AND_CHEATED BattleBehavior = 3
	BattleBehavior_BEHAVIOR_NO_CONTEST               BattleBehavior = 4
)

// Enum value maps for BattleBehavior.
var (
	BattleBehavior_name = map[int32]string{
		0: "BATTLE_BEHAVIOR_UNSPECIFIED",
		// Duplicate value: 0: "BEHAVIOR_SUCCESSFUL",
		1: "BEHAVIOR_DISCONNECTED",
		2: "BEHAVIOR_CHEATED",
		3: "BEHAVIOR_DISCONNECTED_AND_CHEATED",
		4: "BEHAVIOR_NO_CONTEST",
	}
	BattleBehavior_value = map[string]int32{
		"BATTLE_BEHAVIOR_UNSPECIFIED":       0,
		"BEHAVIOR_SUCCESSFUL":               0,
		"BEHAVIOR_DISCONNECTED":             1,
		"BEHAVIOR_CHEATED":                  2,
		"BEHAVIOR_DISCONNECTED_AND_CHEATED": 3,
		"BEHAVIOR_NO_CONTEST":               4,
	}
)

func (x BattleBehavior) Enum() *BattleBehavior {
	p := new(BattleBehavior)
	*p = x
	return p
}

func (x BattleBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ikaros_v1_resources_proto_enumTypes[0].Descriptor()
}

func (BattleBehavior) Type() protoreflect.EnumType {
	return &file_proto_ikaros_v1_resources_proto_enumTypes[0]
}

func (x BattleBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleBehavior.Descriptor instead.
func (BattleBehavior) EnumDescriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{0}
}

type BattleResult int32

const (
	BattleResult_BATTLE_RESULT_UNSPECIFIED BattleResult = 0
	BattleResult_BATTLE_LOSE               BattleResult = 0
	BattleResult_BATTLE_WIN                BattleResult = 1
	BattleResult_BATTLE_DRAW               BattleResult = 2
	BattleResult_BATTLE_NO_CONTEST         BattleResult = 3
)

// Enum value maps for BattleResult.
var (
	BattleResult_name = map[int32]string{
		0: "BATTLE_RESULT_UNSPECIFIED",
		// Duplicate value: 0: "BATTLE_LOSE",
		1: "BATTLE_WIN",
		2: "BATTLE_DRAW",
		3: "BATTLE_NO_CONTEST",
	}
	BattleResult_value = map[string]int32{
		"BATTLE_RESULT_UNSPECIFIED": 0,
		"BATTLE_LOSE":               0,
		"BATTLE_WIN":                1,
		"BATTLE_DRAW":               2,
		"BATTLE_NO_CONTEST":         3,
	}
)

func (x BattleResult) Enum() *BattleResult {
	p := new(BattleResult)
	*p = x
	return p
}

func (x BattleResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleResult) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ikaros_v1_resources_proto_enumTypes[1].Descriptor()
}

func (BattleResult) Type() protoreflect.EnumType {
	return &file_proto_ikaros_v1_resources_proto_enumTypes[1]
}

func (x BattleResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleResult.Descriptor instead.
func (BattleResult) EnumDescriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{1}
}

type CompetitionType int32

const (
	CompetitionType_COMPETITION_TYPE_UNSPECIFIED CompetitionType = 0
	CompetitionType_OFFICIAL                     CompetitionType = 1
	CompetitionType_FRIENDLY                     CompetitionType = 2
	CompetitionType_RANKED_SINGLES               CompetitionType = 3
	CompetitionType_RANKED_DOUBLES               CompetitionType = 4
	CompetitionType_CASUAL                       CompetitionType = 5
)

// Enum value maps for CompetitionType.
var (
	CompetitionType_name = map[int32]string{
		0: "COMPETITION_TYPE_UNSPECIFIED",
		1: "OFFICIAL",
		2: "FRIENDLY",
		3: "RANKED_SINGLES",
		4: "RANKED_DOUBLES",
		5: "CASUAL",
	}
	CompetitionType_value = map[string]int32{
		"COMPETITION_TYPE_UNSPECIFIED": 0,
		"OFFICIAL":                     1,
		"FRIENDLY":                     2,
		"RANKED_SINGLES":               3,
		"RANKED_DOUBLES":               4,
		"CASUAL":                       5,
	}
)

func (x CompetitionType) Enum() *CompetitionType {
	p := new(CompetitionType)
	*p = x
	return p
}

func (x CompetitionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompetitionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ikaros_v1_resources_proto_enumTypes[2].Descriptor()
}

func (CompetitionType) Type() protoreflect.EnumType {
	return &file_proto_ikaros_v1_resources_proto_enumTypes[2]
}

func (x CompetitionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompetitionType.Descriptor instead.
func (CompetitionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{2}
}

type CompetitionUserCategory int32

const (
	CompetitionUserCategory_COMPETITION_USER_CATEGORY_UNSPECIFIED CompetitionUserCategory = 0
	CompetitionUserCategory_JUNIOR                                CompetitionUserCategory = 1
	CompetitionUserCategory_SENIOR                                CompetitionUserCategory = 2
	CompetitionUserCategory_MASTER                                CompetitionUserCategory = 3
)

// Enum value maps for CompetitionUserCategory.
var (
	CompetitionUserCategory_name = map[int32]string{
		0: "COMPETITION_USER_CATEGORY_UNSPECIFIED",
		1: "JUNIOR",
		2: "SENIOR",
		3: "MASTER",
	}
	CompetitionUserCategory_value = map[string]int32{
		"COMPETITION_USER_CATEGORY_UNSPECIFIED": 0,
		"JUNIOR":                                1,
		"SENIOR":                                2,
		"MASTER":                                3,
	}
)

func (x CompetitionUserCategory) Enum() *CompetitionUserCategory {
	p := new(CompetitionUserCategory)
	*p = x
	return p
}

func (x CompetitionUserCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompetitionUserCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ikaros_v1_resources_proto_enumTypes[3].Descriptor()
}

func (CompetitionUserCategory) Type() protoreflect.EnumType {
	return &file_proto_ikaros_v1_resources_proto_enumTypes[3]
}

func (x CompetitionUserCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompetitionUserCategory.Descriptor instead.
func (CompetitionUserCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{3}
}

type CompetitionView int32

const (
	CompetitionView_COMPETITION_VIEW_UNSPECIFIED CompetitionView = 0
	CompetitionView_BASIC                        CompetitionView = 1
	CompetitionView_FULL                         CompetitionView = 2
	CompetitionView_SMALL                        CompetitionView = 3
)

// Enum value maps for CompetitionView.
var (
	CompetitionView_name = map[int32]string{
		0: "COMPETITION_VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "FULL",
		3: "SMALL",
	}
	CompetitionView_value = map[string]int32{
		"COMPETITION_VIEW_UNSPECIFIED": 0,
		"BASIC":                        1,
		"FULL":                         2,
		"SMALL":                        3,
	}
)

func (x CompetitionView) Enum() *CompetitionView {
	p := new(CompetitionView)
	*p = x
	return p
}

func (x CompetitionView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompetitionView) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ikaros_v1_resources_proto_enumTypes[4].Descriptor()
}

func (CompetitionView) Type() protoreflect.EnumType {
	return &file_proto_ikaros_v1_resources_proto_enumTypes[4]
}

func (x CompetitionView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompetitionView.Descriptor instead.
func (CompetitionView) EnumDescriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{4}
}

type InviteeType int32

const (
	InviteeType_INVITEE_TYPE_UNSPECIFIED InviteeType = 0
	InviteeType_PLAYER                   InviteeType = 1
	InviteeType_SPECTATOR                InviteeType = 2
)

// Enum value maps for InviteeType.
var (
	InviteeType_name = map[int32]string{
		0: "INVITEE_TYPE_UNSPECIFIED",
		1: "PLAYER",
		2: "SPECTATOR",
	}
	InviteeType_value = map[string]int32{
		"INVITEE_TYPE_UNSPECIFIED": 0,
		"PLAYER":                   1,
		"SPECTATOR":                2,
	}
)

func (x InviteeType) Enum() *InviteeType {
	p := new(InviteeType)
	*p = x
	return p
}

func (x InviteeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InviteeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ikaros_v1_resources_proto_enumTypes[5].Descriptor()
}

func (InviteeType) Type() protoreflect.EnumType {
	return &file_proto_ikaros_v1_resources_proto_enumTypes[5]
}

func (x InviteeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InviteeType.Descriptor instead.
func (InviteeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{5}
}

type MatchingKeyCreator int32

const (
	MatchingKeyCreator_MATCHING_KEY_CREATOR_UNSPECIFIED MatchingKeyCreator = 0
	MatchingKeyCreator_SERVER                           MatchingKeyCreator = 1
	MatchingKeyCreator_OPERATOR                         MatchingKeyCreator = 2
)

// Enum value maps for MatchingKeyCreator.
var (
	MatchingKeyCreator_name = map[int32]string{
		0: "MATCHING_KEY_CREATOR_UNSPECIFIED",
		1: "SERVER",
		2: "OPERATOR",
	}
	MatchingKeyCreator_value = map[string]int32{
		"MATCHING_KEY_CREATOR_UNSPECIFIED": 0,
		"SERVER":                           1,
		"OPERATOR":                         2,
	}
)

func (x MatchingKeyCreator) Enum() *MatchingKeyCreator {
	p := new(MatchingKeyCreator)
	*p = x
	return p
}

func (x MatchingKeyCreator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchingKeyCreator) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ikaros_v1_resources_proto_enumTypes[6].Descriptor()
}

func (MatchingKeyCreator) Type() protoreflect.EnumType {
	return &file_proto_ikaros_v1_resources_proto_enumTypes[6]
}

func (x MatchingKeyCreator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchingKeyCreator.Descriptor instead.
func (MatchingKeyCreator) EnumDescriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{6}
}

type Permission int32

const (
	Permission_PERMISSION_UNSPECIFIED Permission = 0
	Permission_OWNER                  Permission = 1
	Permission_INVITEES               Permission = 2
	Permission_ANYBODY                Permission = 3
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0: "PERMISSION_UNSPECIFIED",
		1: "OWNER",
		2: "INVITEES",
		3: "ANYBODY",
	}
	Permission_value = map[string]int32{
		"PERMISSION_UNSPECIFIED": 0,
		"OWNER":                  1,
		"INVITEES":               2,
		"ANYBODY":                3,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ikaros_v1_resources_proto_enumTypes[7].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_proto_ikaros_v1_resources_proto_enumTypes[7]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{7}
}

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_ACCEPTED          State = 1
	State_ACTIVE            State = 2
	State_INACTIVE          State = 3
	State_CANCELLED         State = 4
	State_DELETED           State = 5
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "ACCEPTED",
		2: "ACTIVE",
		3: "INACTIVE",
		4: "CANCELLED",
		5: "DELETED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"ACCEPTED":          1,
		"ACTIVE":            2,
		"INACTIVE":          3,
		"CANCELLED":         4,
		"DELETED":           5,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ikaros_v1_resources_proto_enumTypes[8].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_ikaros_v1_resources_proto_enumTypes[8]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{8}
}

type BattleDataLog struct {
	state                   protoimpl.MessageState  `protogen:"open.v1"`
	Name                    string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Competition             string                  `protobuf:"bytes,2,opt,name=competition,proto3" json:"competition,omitempty"`
	CompetitionType         CompetitionType         `protobuf:"varint,3,opt,name=competition_type,json=competitionType,proto3,enum=nn.npln.ikaros.v1.CompetitionType" json:"competition_type,omitempty"`
	NormalizedBattleResults []*PersonalBattleResult `protobuf:"bytes,4,rep,name=normalized_battle_results,json=normalizedBattleResults,proto3" json:"normalized_battle_results,omitempty"`
	CreateTime              *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	BattleReports           []*BattleReport         `protobuf:"bytes,6,rep,name=battle_reports,json=battleReports,proto3" json:"battle_reports,omitempty"`
	MatchingKey             string                  `protobuf:"bytes,7,opt,name=matching_key,json=matchingKey,proto3" json:"matching_key,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BattleDataLog) Reset() {
	*x = BattleDataLog{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleDataLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleDataLog) ProtoMessage() {}

func (x *BattleDataLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleDataLog.ProtoReflect.Descriptor instead.
func (*BattleDataLog) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{0}
}

func (x *BattleDataLog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BattleDataLog) GetCompetition() string {
	if x != nil {
		return x.Competition
	}
	return ""
}

func (x *BattleDataLog) GetCompetitionType() CompetitionType {
	if x != nil {
		return x.CompetitionType
	}
	return CompetitionType_COMPETITION_TYPE_UNSPECIFIED
}

func (x *BattleDataLog) GetNormalizedBattleResults() []*PersonalBattleResult {
	if x != nil {
		return x.NormalizedBattleResults
	}
	return nil
}

func (x *BattleDataLog) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *BattleDataLog) GetBattleReports() []*BattleReport {
	if x != nil {
		return x.BattleReports
	}
	return nil
}

func (x *BattleDataLog) GetMatchingKey() string {
	if x != nil {
		return x.MatchingKey
	}
	return ""
}

type BattleReport struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	Reporter              string                  `protobuf:"bytes,1,opt,name=reporter,proto3" json:"reporter,omitempty"`
	PersonalBattleResults []*PersonalBattleResult `protobuf:"bytes,2,rep,name=personal_battle_results,json=personalBattleResults,proto3" json:"personal_battle_results,omitempty"`
	Log                   []byte                  `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BattleReport) Reset() {
	*x = BattleReport{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleReport) ProtoMessage() {}

func (x *BattleReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleReport.ProtoReflect.Descriptor instead.
func (*BattleReport) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{1}
}

func (x *BattleReport) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *BattleReport) GetPersonalBattleResults() []*PersonalBattleResult {
	if x != nil {
		return x.PersonalBattleResults
	}
	return nil
}

func (x *BattleReport) GetLog() []byte {
	if x != nil {
		return x.Log
	}
	return nil
}

type Competition struct {
	state                    protoimpl.MessageState    `protogen:"open.v1"`
	Name                     string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CompetitionAlias         string                    `protobuf:"bytes,2,opt,name=competition_alias,json=competitionAlias,proto3" json:"competition_alias,omitempty"`
	CompetitionType          CompetitionType           `protobuf:"varint,33,opt,name=competition_type,json=competitionType,proto3,enum=nn.npln.ikaros.v1.CompetitionType" json:"competition_type,omitempty"`
	Season                   int32                     `protobuf:"varint,5,opt,name=season,proto3" json:"season,omitempty"`
	MainTitles               map[string]string         `protobuf:"bytes,6,rep,name=main_titles,json=mainTitles,proto3" json:"main_titles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SubTitles                map[string]string         `protobuf:"bytes,7,rep,name=sub_titles,json=subTitles,proto3" json:"sub_titles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ReadPermission           Permission                `protobuf:"varint,8,opt,name=read_permission,json=readPermission,proto3,enum=nn.npln.ikaros.v1.Permission" json:"read_permission,omitempty"`
	WritePermission          Permission                `protobuf:"varint,9,opt,name=write_permission,json=writePermission,proto3,enum=nn.npln.ikaros.v1.Permission" json:"write_permission,omitempty"`
	Searchable               bool                      `protobuf:"varint,10,opt,name=searchable,proto3" json:"searchable,omitempty"`
	ParticipantAreas         []int32                   `protobuf:"varint,11,rep,packed,name=participant_areas,json=participantAreas,proto3" json:"participant_areas,omitempty"`
	ParticipantCategories    []CompetitionUserCategory `protobuf:"varint,34,rep,packed,name=participant_categories,json=participantCategories,proto3,enum=nn.npln.ikaros.v1.CompetitionUserCategory" json:"participant_categories,omitempty"`
	MaxParticipantBirthmonth string                    `protobuf:"bytes,12,opt,name=max_participant_birthmonth,json=maxParticipantBirthmonth,proto3" json:"max_participant_birthmonth,omitempty"`
	MinParticipantBirthmonth string                    `protobuf:"bytes,13,opt,name=min_participant_birthmonth,json=minParticipantBirthmonth,proto3" json:"min_participant_birthmonth,omitempty"`
	ParticipantCount         int32                     `protobuf:"varint,14,opt,name=participant_count,json=participantCount,proto3" json:"participant_count,omitempty"`
	MaxParticipantCount      int32                     `protobuf:"varint,15,opt,name=max_participant_count,json=maxParticipantCount,proto3" json:"max_participant_count,omitempty"`
	MinParticipantCount      int32                     `protobuf:"varint,16,opt,name=min_participant_count,json=minParticipantCount,proto3" json:"min_participant_count,omitempty"`
	MatchmakingConfig        string                    `protobuf:"bytes,17,opt,name=matchmaking_config,json=matchmakingConfig,proto3" json:"matchmaking_config,omitempty"`
	MatchingKeyCreator       MatchingKeyCreator        `protobuf:"varint,18,opt,name=matching_key_creator,json=matchingKeyCreator,proto3,enum=nn.npln.ikaros.v1.MatchingKeyCreator" json:"matching_key_creator,omitempty"`
	MatchingHours            []int32                   `protobuf:"varint,19,rep,packed,name=matching_hours,json=matchingHours,proto3" json:"matching_hours,omitempty"`
	MaxMatchCount            int32                     `protobuf:"varint,20,opt,name=max_match_count,json=maxMatchCount,proto3" json:"max_match_count,omitempty"`
	MaxDailyMatchCount       int32                     `protobuf:"varint,21,opt,name=max_daily_match_count,json=maxDailyMatchCount,proto3" json:"max_daily_match_count,omitempty"`
	RequiredMatchCount       int32                     `protobuf:"varint,35,opt,name=required_match_count,json=requiredMatchCount,proto3" json:"required_match_count,omitempty"`
	Maintenance              int32                     `protobuf:"varint,22,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	ExplicitFinalization     bool                      `protobuf:"varint,23,opt,name=explicit_finalization,json=explicitFinalization,proto3" json:"explicit_finalization,omitempty"`
	ApplicationData          *common.MapValue          `protobuf:"bytes,24,opt,name=application_data,json=applicationData,proto3" json:"application_data,omitempty"`
	CreateTime               *timestamppb.Timestamp    `protobuf:"bytes,25,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime               *timestamppb.Timestamp    `protobuf:"bytes,36,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	StartParticipateTime     *timestamppb.Timestamp    `protobuf:"bytes,26,opt,name=start_participate_time,json=startParticipateTime,proto3" json:"start_participate_time,omitempty"`
	EndParticipateTime       *timestamppb.Timestamp    `protobuf:"bytes,27,opt,name=end_participate_time,json=endParticipateTime,proto3" json:"end_participate_time,omitempty"`
	StartBattleTime          *timestamppb.Timestamp    `protobuf:"bytes,28,opt,name=start_battle_time,json=startBattleTime,proto3" json:"start_battle_time,omitempty"`
	EndBattleTime            *timestamppb.Timestamp    `protobuf:"bytes,29,opt,name=end_battle_time,json=endBattleTime,proto3" json:"end_battle_time,omitempty"`
	AggregateTime            *timestamppb.Timestamp    `protobuf:"bytes,30,opt,name=aggregate_time,json=aggregateTime,proto3" json:"aggregate_time,omitempty"`
	FinalizeTime             *timestamppb.Timestamp    `protobuf:"bytes,31,opt,name=finalize_time,json=finalizeTime,proto3" json:"finalize_time,omitempty"`
	OwnerParticipant         string                    `protobuf:"bytes,32,opt,name=owner_participant,json=ownerParticipant,proto3" json:"owner_participant,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Competition) Reset() {
	*x = Competition{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Competition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Competition) ProtoMessage() {}

func (x *Competition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Competition.ProtoReflect.Descriptor instead.
func (*Competition) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{2}
}

func (x *Competition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Competition) GetCompetitionAlias() string {
	if x != nil {
		return x.CompetitionAlias
	}
	return ""
}

func (x *Competition) GetCompetitionType() CompetitionType {
	if x != nil {
		return x.CompetitionType
	}
	return CompetitionType_COMPETITION_TYPE_UNSPECIFIED
}

func (x *Competition) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *Competition) GetMainTitles() map[string]string {
	if x != nil {
		return x.MainTitles
	}
	return nil
}

func (x *Competition) GetSubTitles() map[string]string {
	if x != nil {
		return x.SubTitles
	}
	return nil
}

func (x *Competition) GetReadPermission() Permission {
	if x != nil {
		return x.ReadPermission
	}
	return Permission_PERMISSION_UNSPECIFIED
}

func (x *Competition) GetWritePermission() Permission {
	if x != nil {
		return x.WritePermission
	}
	return Permission_PERMISSION_UNSPECIFIED
}

func (x *Competition) GetSearchable() bool {
	if x != nil {
		return x.Searchable
	}
	return false
}

func (x *Competition) GetParticipantAreas() []int32 {
	if x != nil {
		return x.ParticipantAreas
	}
	return nil
}

func (x *Competition) GetParticipantCategories() []CompetitionUserCategory {
	if x != nil {
		return x.ParticipantCategories
	}
	return nil
}

func (x *Competition) GetMaxParticipantBirthmonth() string {
	if x != nil {
		return x.MaxParticipantBirthmonth
	}
	return ""
}

func (x *Competition) GetMinParticipantBirthmonth() string {
	if x != nil {
		return x.MinParticipantBirthmonth
	}
	return ""
}

func (x *Competition) GetParticipantCount() int32 {
	if x != nil {
		return x.ParticipantCount
	}
	return 0
}

func (x *Competition) GetMaxParticipantCount() int32 {
	if x != nil {
		return x.MaxParticipantCount
	}
	return 0
}

func (x *Competition) GetMinParticipantCount() int32 {
	if x != nil {
		return x.MinParticipantCount
	}
	return 0
}

func (x *Competition) GetMatchmakingConfig() string {
	if x != nil {
		return x.MatchmakingConfig
	}
	return ""
}

func (x *Competition) GetMatchingKeyCreator() MatchingKeyCreator {
	if x != nil {
		return x.MatchingKeyCreator
	}
	return MatchingKeyCreator_MATCHING_KEY_CREATOR_UNSPECIFIED
}

func (x *Competition) GetMatchingHours() []int32 {
	if x != nil {
		return x.MatchingHours
	}
	return nil
}

func (x *Competition) GetMaxMatchCount() int32 {
	if x != nil {
		return x.MaxMatchCount
	}
	return 0
}

func (x *Competition) GetMaxDailyMatchCount() int32 {
	if x != nil {
		return x.MaxDailyMatchCount
	}
	return 0
}

func (x *Competition) GetRequiredMatchCount() int32 {
	if x != nil {
		return x.RequiredMatchCount
	}
	return 0
}

func (x *Competition) GetMaintenance() int32 {
	if x != nil {
		return x.Maintenance
	}
	return 0
}

func (x *Competition) GetExplicitFinalization() bool {
	if x != nil {
		return x.ExplicitFinalization
	}
	return false
}

func (x *Competition) GetApplicationData() *common.MapValue {
	if x != nil {
		return x.ApplicationData
	}
	return nil
}

func (x *Competition) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Competition) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Competition) GetStartParticipateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartParticipateTime
	}
	return nil
}

func (x *Competition) GetEndParticipateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndParticipateTime
	}
	return nil
}

func (x *Competition) GetStartBattleTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartBattleTime
	}
	return nil
}

func (x *Competition) GetEndBattleTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndBattleTime
	}
	return nil
}

func (x *Competition) GetAggregateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AggregateTime
	}
	return nil
}

func (x *Competition) GetFinalizeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FinalizeTime
	}
	return nil
}

func (x *Competition) GetOwnerParticipant() string {
	if x != nil {
		return x.OwnerParticipant
	}
	return ""
}

type CompetitionAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Competition   string                 `protobuf:"bytes,2,opt,name=competition,proto3" json:"competition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionAlias) Reset() {
	*x = CompetitionAlias{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionAlias) ProtoMessage() {}

func (x *CompetitionAlias) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionAlias.ProtoReflect.Descriptor instead.
func (*CompetitionAlias) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{3}
}

func (x *CompetitionAlias) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompetitionAlias) GetCompetition() string {
	if x != nil {
		return x.Competition
	}
	return ""
}

type CompetitionAlternativeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	Etag          string                 `protobuf:"bytes,99,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionAlternativeResult) Reset() {
	*x = CompetitionAlternativeResult{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionAlternativeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionAlternativeResult) ProtoMessage() {}

func (x *CompetitionAlternativeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionAlternativeResult.ProtoReflect.Descriptor instead.
func (*CompetitionAlternativeResult) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{4}
}

func (x *CompetitionAlternativeResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompetitionAlternativeResult) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CompetitionAlternativeResult) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type CompetitionInvitation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InviteeType   InviteeType            `protobuf:"varint,2,opt,name=invitee_type,json=inviteeType,proto3,enum=nn.npln.ikaros.v1.InviteeType" json:"invitee_type,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionInvitation) Reset() {
	*x = CompetitionInvitation{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionInvitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionInvitation) ProtoMessage() {}

func (x *CompetitionInvitation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionInvitation.ProtoReflect.Descriptor instead.
func (*CompetitionInvitation) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{5}
}

func (x *CompetitionInvitation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompetitionInvitation) GetInviteeType() InviteeType {
	if x != nil {
		return x.InviteeType
	}
	return InviteeType_INVITEE_TYPE_UNSPECIFIED
}

func (x *CompetitionInvitation) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type CompetitionNotification struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Etag       string                 `protobuf:"bytes,99,opt,name=etag,proto3" json:"etag,omitempty"`
	// Types that are valid to be assigned to Notification:
	//
	//	*CompetitionNotification_Invalid
	//	*CompetitionNotification_MatchingKey
	//	*CompetitionNotification_Schedule
	//	*CompetitionNotification_Elimination
	Notification  isCompetitionNotification_Notification `protobuf_oneof:"notification"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionNotification) Reset() {
	*x = CompetitionNotification{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionNotification) ProtoMessage() {}

func (x *CompetitionNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionNotification.ProtoReflect.Descriptor instead.
func (*CompetitionNotification) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{6}
}

func (x *CompetitionNotification) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompetitionNotification) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *CompetitionNotification) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *CompetitionNotification) GetNotification() isCompetitionNotification_Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *CompetitionNotification) GetInvalid() *CompetitionNotification_CompetitionInvalidNotification {
	if x != nil {
		if x, ok := x.Notification.(*CompetitionNotification_Invalid); ok {
			return x.Invalid
		}
	}
	return nil
}

func (x *CompetitionNotification) GetMatchingKey() string {
	if x != nil {
		if x, ok := x.Notification.(*CompetitionNotification_MatchingKey); ok {
			return x.MatchingKey
		}
	}
	return ""
}

func (x *CompetitionNotification) GetSchedule() *CompetitionNotification_CompetitionScheduleNotification {
	if x != nil {
		if x, ok := x.Notification.(*CompetitionNotification_Schedule); ok {
			return x.Schedule
		}
	}
	return nil
}

func (x *CompetitionNotification) GetElimination() *CompetitionNotification_CompetitionEliminationNotification {
	if x != nil {
		if x, ok := x.Notification.(*CompetitionNotification_Elimination); ok {
			return x.Elimination
		}
	}
	return nil
}

type isCompetitionNotification_Notification interface {
	isCompetitionNotification_Notification()
}

type CompetitionNotification_Invalid struct {
	Invalid *CompetitionNotification_CompetitionInvalidNotification `protobuf:"bytes,3,opt,name=invalid,proto3,oneof"`
}

type CompetitionNotification_MatchingKey struct {
	MatchingKey string `protobuf:"bytes,4,opt,name=matching_key,json=matchingKey,proto3,oneof"`
}

type CompetitionNotification_Schedule struct {
	Schedule *CompetitionNotification_CompetitionScheduleNotification `protobuf:"bytes,5,opt,name=schedule,proto3,oneof"`
}

type CompetitionNotification_Elimination struct {
	Elimination *CompetitionNotification_CompetitionEliminationNotification `protobuf:"bytes,6,opt,name=elimination,proto3,oneof"`
}

func (*CompetitionNotification_Invalid) isCompetitionNotification_Notification() {}

func (*CompetitionNotification_MatchingKey) isCompetitionNotification_Notification() {}

func (*CompetitionNotification_Schedule) isCompetitionNotification_Notification() {}

func (*CompetitionNotification_Elimination) isCompetitionNotification_Notification() {}

type CompetitionParticipant struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Name              string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slot              int32                   `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	DeviceId          string                  `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UtcOffset         string                  `protobuf:"bytes,4,opt,name=utc_offset,json=utcOffset,proto3" json:"utc_offset,omitempty"`
	ParticipantBinary []byte                  `protobuf:"bytes,5,opt,name=participant_binary,json=participantBinary,proto3" json:"participant_binary,omitempty"`
	State             State                   `protobuf:"varint,6,opt,name=state,proto3,enum=nn.npln.ikaros.v1.State" json:"state,omitempty"`
	CreateTime        *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ActivateTime      *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=activate_time,json=activateTime,proto3" json:"activate_time,omitempty"`
	DeactivateTime    *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=deactivate_time,json=deactivateTime,proto3" json:"deactivate_time,omitempty"`
	CancelTime        *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=cancel_time,json=cancelTime,proto3" json:"cancel_time,omitempty"`
	DeleteTime        *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=delete_time,json=deleteTime,proto3" json:"delete_time,omitempty"`
	Finalized         bool                    `protobuf:"varint,12,opt,name=finalized,proto3" json:"finalized,omitempty"`
	Rating            int32                   `protobuf:"varint,13,opt,name=rating,proto3" json:"rating,omitempty"`
	Rank              int32                   `protobuf:"varint,14,opt,name=rank,proto3" json:"rank,omitempty"`
	MatchCount        int32                   `protobuf:"varint,15,opt,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`
	WinCount          int32                   `protobuf:"varint,16,opt,name=win_count,json=winCount,proto3" json:"win_count,omitempty"`
	LoseCount         int32                   `protobuf:"varint,17,opt,name=lose_count,json=loseCount,proto3" json:"lose_count,omitempty"`
	DrawCount         int32                   `protobuf:"varint,18,opt,name=draw_count,json=drawCount,proto3" json:"draw_count,omitempty"`
	DisconnectCount   int32                   `protobuf:"varint,19,opt,name=disconnect_count,json=disconnectCount,proto3" json:"disconnect_count,omitempty"`
	NoContestCount    int32                   `protobuf:"varint,20,opt,name=no_contest_count,json=noContestCount,proto3" json:"no_contest_count,omitempty"`
	WinStreakCount    int32                   `protobuf:"varint,21,opt,name=win_streak_count,json=winStreakCount,proto3" json:"win_streak_count,omitempty"`
	LoseStreakCount   int32                   `protobuf:"varint,22,opt,name=lose_streak_count,json=loseStreakCount,proto3" json:"lose_streak_count,omitempty"`
	Point             int32                   `protobuf:"varint,23,opt,name=point,proto3" json:"point,omitempty"`
	MaxPoint          int32                   `protobuf:"varint,24,opt,name=max_point,json=maxPoint,proto3" json:"max_point,omitempty"`
	Category          CompetitionUserCategory `protobuf:"varint,25,opt,name=category,proto3,enum=nn.npln.ikaros.v1.CompetitionUserCategory" json:"category,omitempty"`
	Area              int32                   `protobuf:"varint,26,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompetitionParticipant) Reset() {
	*x = CompetitionParticipant{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionParticipant) ProtoMessage() {}

func (x *CompetitionParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionParticipant.ProtoReflect.Descriptor instead.
func (*CompetitionParticipant) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{7}
}

func (x *CompetitionParticipant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompetitionParticipant) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CompetitionParticipant) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CompetitionParticipant) GetUtcOffset() string {
	if x != nil {
		return x.UtcOffset
	}
	return ""
}

func (x *CompetitionParticipant) GetParticipantBinary() []byte {
	if x != nil {
		return x.ParticipantBinary
	}
	return nil
}

func (x *CompetitionParticipant) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *CompetitionParticipant) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CompetitionParticipant) GetActivateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ActivateTime
	}
	return nil
}

func (x *CompetitionParticipant) GetDeactivateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeactivateTime
	}
	return nil
}

func (x *CompetitionParticipant) GetCancelTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelTime
	}
	return nil
}

func (x *CompetitionParticipant) GetDeleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteTime
	}
	return nil
}

func (x *CompetitionParticipant) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

func (x *CompetitionParticipant) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CompetitionParticipant) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CompetitionParticipant) GetMatchCount() int32 {
	if x != nil {
		return x.MatchCount
	}
	return 0
}

func (x *CompetitionParticipant) GetWinCount() int32 {
	if x != nil {
		return x.WinCount
	}
	return 0
}

func (x *CompetitionParticipant) GetLoseCount() int32 {
	if x != nil {
		return x.LoseCount
	}
	return 0
}

func (x *CompetitionParticipant) GetDrawCount() int32 {
	if x != nil {
		return x.DrawCount
	}
	return 0
}

func (x *CompetitionParticipant) GetDisconnectCount() int32 {
	if x != nil {
		return x.DisconnectCount
	}
	return 0
}

func (x *CompetitionParticipant) GetNoContestCount() int32 {
	if x != nil {
		return x.NoContestCount
	}
	return 0
}

func (x *CompetitionParticipant) GetWinStreakCount() int32 {
	if x != nil {
		return x.WinStreakCount
	}
	return 0
}

func (x *CompetitionParticipant) GetLoseStreakCount() int32 {
	if x != nil {
		return x.LoseStreakCount
	}
	return 0
}

func (x *CompetitionParticipant) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *CompetitionParticipant) GetMaxPoint() int32 {
	if x != nil {
		return x.MaxPoint
	}
	return 0
}

func (x *CompetitionParticipant) GetCategory() CompetitionUserCategory {
	if x != nil {
		return x.Category
	}
	return CompetitionUserCategory_COMPETITION_USER_CATEGORY_UNSPECIFIED
}

func (x *CompetitionParticipant) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

type CompetitionUser struct {
	state                           protoimpl.MessageState       `protogen:"open.v1"`
	Name                            string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category                        CompetitionUserCategory      `protobuf:"varint,14,opt,name=category,proto3,enum=nn.npln.ikaros.v1.CompetitionUserCategory" json:"category,omitempty"`
	Birthmonth                      string                       `protobuf:"bytes,2,opt,name=birthmonth,proto3" json:"birthmonth,omitempty"`
	Area                            int32                        `protobuf:"varint,3,opt,name=area,proto3" json:"area,omitempty"`
	LanguageCode                    string                       `protobuf:"bytes,4,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	CurrentOfficialCompetition      string                       `protobuf:"bytes,5,opt,name=current_official_competition,json=currentOfficialCompetition,proto3" json:"current_official_competition,omitempty"`
	LastOfficialCompetition         string                       `protobuf:"bytes,6,opt,name=last_official_competition,json=lastOfficialCompetition,proto3" json:"last_official_competition,omitempty"`
	CurrentFriendlyCompetition      string                       `protobuf:"bytes,7,opt,name=current_friendly_competition,json=currentFriendlyCompetition,proto3" json:"current_friendly_competition,omitempty"`
	LastFriendlyCompetition         string                       `protobuf:"bytes,8,opt,name=last_friendly_competition,json=lastFriendlyCompetition,proto3" json:"last_friendly_competition,omitempty"`
	CurrentRankedSinglesCompetition string                       `protobuf:"bytes,15,opt,name=current_ranked_singles_competition,json=currentRankedSinglesCompetition,proto3" json:"current_ranked_singles_competition,omitempty"`
	LastRankedSinglesCompetition    string                       `protobuf:"bytes,16,opt,name=last_ranked_singles_competition,json=lastRankedSinglesCompetition,proto3" json:"last_ranked_singles_competition,omitempty"`
	CurrentRankedDoublesCompetition string                       `protobuf:"bytes,17,opt,name=current_ranked_doubles_competition,json=currentRankedDoublesCompetition,proto3" json:"current_ranked_doubles_competition,omitempty"`
	LastRankedDoublesCompetition    string                       `protobuf:"bytes,18,opt,name=last_ranked_doubles_competition,json=lastRankedDoublesCompetition,proto3" json:"last_ranked_doubles_competition,omitempty"`
	BattleStats                     *CompetitionUser_BattleStats `protobuf:"bytes,13,opt,name=battle_stats,json=battleStats,proto3" json:"battle_stats,omitempty"`
	CreateTime                      *timestamppb.Timestamp       `protobuf:"bytes,19,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *CompetitionUser) Reset() {
	*x = CompetitionUser{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionUser) ProtoMessage() {}

func (x *CompetitionUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionUser.ProtoReflect.Descriptor instead.
func (*CompetitionUser) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{8}
}

func (x *CompetitionUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompetitionUser) GetCategory() CompetitionUserCategory {
	if x != nil {
		return x.Category
	}
	return CompetitionUserCategory_COMPETITION_USER_CATEGORY_UNSPECIFIED
}

func (x *CompetitionUser) GetBirthmonth() string {
	if x != nil {
		return x.Birthmonth
	}
	return ""
}

func (x *CompetitionUser) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *CompetitionUser) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *CompetitionUser) GetCurrentOfficialCompetition() string {
	if x != nil {
		return x.CurrentOfficialCompetition
	}
	return ""
}

func (x *CompetitionUser) GetLastOfficialCompetition() string {
	if x != nil {
		return x.LastOfficialCompetition
	}
	return ""
}

func (x *CompetitionUser) GetCurrentFriendlyCompetition() string {
	if x != nil {
		return x.CurrentFriendlyCompetition
	}
	return ""
}

func (x *CompetitionUser) GetLastFriendlyCompetition() string {
	if x != nil {
		return x.LastFriendlyCompetition
	}
	return ""
}

func (x *CompetitionUser) GetCurrentRankedSinglesCompetition() string {
	if x != nil {
		return x.CurrentRankedSinglesCompetition
	}
	return ""
}

func (x *CompetitionUser) GetLastRankedSinglesCompetition() string {
	if x != nil {
		return x.LastRankedSinglesCompetition
	}
	return ""
}

func (x *CompetitionUser) GetCurrentRankedDoublesCompetition() string {
	if x != nil {
		return x.CurrentRankedDoublesCompetition
	}
	return ""
}

func (x *CompetitionUser) GetLastRankedDoublesCompetition() string {
	if x != nil {
		return x.LastRankedDoublesCompetition
	}
	return ""
}

func (x *CompetitionUser) GetBattleStats() *CompetitionUser_BattleStats {
	if x != nil {
		return x.BattleStats
	}
	return nil
}

func (x *CompetitionUser) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type CompetitionUserBattleRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Disconnect    bool                   `protobuf:"varint,2,opt,name=disconnect,proto3" json:"disconnect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionUserBattleRecord) Reset() {
	*x = CompetitionUserBattleRecord{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionUserBattleRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionUserBattleRecord) ProtoMessage() {}

func (x *CompetitionUserBattleRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionUserBattleRecord.ProtoReflect.Descriptor instead.
func (*CompetitionUserBattleRecord) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{9}
}

func (x *CompetitionUserBattleRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompetitionUserBattleRecord) GetDisconnect() bool {
	if x != nil {
		return x.Disconnect
	}
	return false
}

type PersonalBattleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Result        BattleResult           `protobuf:"varint,2,opt,name=result,proto3,enum=nn.npln.ikaros.v1.BattleResult" json:"result,omitempty"`
	Behavior      BattleBehavior         `protobuf:"varint,3,opt,name=behavior,proto3,enum=nn.npln.ikaros.v1.BattleBehavior" json:"behavior,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	Point         int32                  `protobuf:"varint,5,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalBattleResult) Reset() {
	*x = PersonalBattleResult{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalBattleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalBattleResult) ProtoMessage() {}

func (x *PersonalBattleResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalBattleResult.ProtoReflect.Descriptor instead.
func (*PersonalBattleResult) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{10}
}

func (x *PersonalBattleResult) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PersonalBattleResult) GetResult() BattleResult {
	if x != nil {
		return x.Result
	}
	return BattleResult_BATTLE_RESULT_UNSPECIFIED
}

func (x *PersonalBattleResult) GetBehavior() BattleBehavior {
	if x != nil {
		return x.Behavior
	}
	return BattleBehavior_BATTLE_BEHAVIOR_UNSPECIFIED
}

func (x *PersonalBattleResult) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *PersonalBattleResult) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

type CompetitionNotification_CompetitionEliminationNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionNotification_CompetitionEliminationNotification) Reset() {
	*x = CompetitionNotification_CompetitionEliminationNotification{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionNotification_CompetitionEliminationNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionNotification_CompetitionEliminationNotification) ProtoMessage() {}

func (x *CompetitionNotification_CompetitionEliminationNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionNotification_CompetitionEliminationNotification.ProtoReflect.Descriptor instead.
func (*CompetitionNotification_CompetitionEliminationNotification) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{6, 0}
}

type CompetitionNotification_CompetitionInvalidNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionNotification_CompetitionInvalidNotification) Reset() {
	*x = CompetitionNotification_CompetitionInvalidNotification{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionNotification_CompetitionInvalidNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionNotification_CompetitionInvalidNotification) ProtoMessage() {}

func (x *CompetitionNotification_CompetitionInvalidNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionNotification_CompetitionInvalidNotification.ProtoReflect.Descriptor instead.
func (*CompetitionNotification_CompetitionInvalidNotification) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{6, 1}
}

type CompetitionNotification_CompetitionScheduleNotification struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StartBattleTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_battle_time,json=startBattleTime,proto3" json:"start_battle_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompetitionNotification_CompetitionScheduleNotification) Reset() {
	*x = CompetitionNotification_CompetitionScheduleNotification{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionNotification_CompetitionScheduleNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionNotification_CompetitionScheduleNotification) ProtoMessage() {}

func (x *CompetitionNotification_CompetitionScheduleNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionNotification_CompetitionScheduleNotification.ProtoReflect.Descriptor instead.
func (*CompetitionNotification_CompetitionScheduleNotification) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{6, 2}
}

func (x *CompetitionNotification_CompetitionScheduleNotification) GetStartBattleTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartBattleTime
	}
	return nil
}

type CompetitionUser_BattleStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BattleCount     int32                  `protobuf:"varint,1,opt,name=battle_count,json=battleCount,proto3" json:"battle_count,omitempty"`
	DisconnectCount int32                  `protobuf:"varint,2,opt,name=disconnect_count,json=disconnectCount,proto3" json:"disconnect_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompetitionUser_BattleStats) Reset() {
	*x = CompetitionUser_BattleStats{}
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionUser_BattleStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionUser_BattleStats) ProtoMessage() {}

func (x *CompetitionUser_BattleStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ikaros_v1_resources_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionUser_BattleStats.ProtoReflect.Descriptor instead.
func (*CompetitionUser_BattleStats) Descriptor() ([]byte, []int) {
	return file_proto_ikaros_v1_resources_proto_rawDescGZIP(), []int{8, 0}
}

func (x *CompetitionUser_BattleStats) GetBattleCount() int32 {
	if x != nil {
		return x.BattleCount
	}
	return 0
}

func (x *CompetitionUser_BattleStats) GetDisconnectCount() int32 {
	if x != nil {
		return x.DisconnectCount
	}
	return 0
}

var File_proto_ikaros_v1_resources_proto protoreflect.FileDescriptor

const file_proto_ikaros_v1_resources_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/ikaros/v1/resources.proto\x12\x11nn.npln.ikaros.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18proto/common/value.proto\"\xa1\x03\n" +
	"\rBattleDataLog\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vcompetition\x18\x02 \x01(\tR\vcompetition\x12M\n" +
	"\x10competition_type\x18\x03 \x01(\x0e2\".nn.npln.ikaros.v1.CompetitionTypeR\x0fcompetitionType\x12c\n" +
	"\x19normalized_battle_results\x18\x04 \x03(\v2'.nn.npln.ikaros.v1.PersonalBattleResultR\x17normalizedBattleResults\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12F\n" +
	"\x0ebattle_reports\x18\x06 \x03(\v2\x1f.nn.npln.ikaros.v1.BattleReportR\rbattleReports\x12!\n" +
	"\fmatching_key\x18\a \x01(\tR\vmatchingKey\"\x9d\x01\n" +
	"\fBattleReport\x12\x1a\n" +
	"\breporter\x18\x01 \x01(\tR\breporter\x12_\n" +
	"\x17personal_battle_results\x18\x02 \x03(\v2'.nn.npln.ikaros.v1.PersonalBattleResultR\x15personalBattleResults\x12\x10\n" +
	"\x03log\x18\x03 \x01(\fR\x03log\"\xdf\x10\n" +
	"\vCompetition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x11competition_alias\x18\x02 \x01(\tR\x10competitionAlias\x12M\n" +
	"\x10competition_type\x18! \x01(\x0e2\".nn.npln.ikaros.v1.CompetitionTypeR\x0fcompetitionType\x12\x16\n" +
	"\x06season\x18\x05 \x01(\x05R\x06season\x12O\n" +
	"\vmain_titles\x18\x06 \x03(\v2..nn.npln.ikaros.v1.Competition.MainTitlesEntryR\n" +
	"mainTitles\x12L\n" +
	"\n" +
	"sub_titles\x18\a \x03(\v2-.nn.npln.ikaros.v1.Competition.SubTitlesEntryR\tsubTitles\x12F\n" +
	"\x0fread_permission\x18\b \x01(\x0e2\x1d.nn.npln.ikaros.v1.PermissionR\x0ereadPermission\x12H\n" +
	"\x10write_permission\x18\t \x01(\x0e2\x1d.nn.npln.ikaros.v1.PermissionR\x0fwritePermission\x12\x1e\n" +
	"\n" +
	"searchable\x18\n" +
	" \x01(\bR\n" +
	"searchable\x12/\n" +
	"\x11participant_areas\x18\v \x03(\x05B\x02\x10\x01R\x10participantAreas\x12e\n" +
	"\x16participant_categories\x18\" \x03(\x0e2*.nn.npln.ikaros.v1.CompetitionUserCategoryB\x02\x10\x01R\x15participantCategories\x12<\n" +
	"\x1amax_participant_birthmonth\x18\f \x01(\tR\x18maxParticipantBirthmonth\x12<\n" +
	"\x1amin_participant_birthmonth\x18\r \x01(\tR\x18minParticipantBirthmonth\x12+\n" +
	"\x11participant_count\x18\x0e \x01(\x05R\x10participantCount\x122\n" +
	"\x15max_participant_count\x18\x0f \x01(\x05R\x13maxParticipantCount\x122\n" +
	"\x15min_participant_count\x18\x10 \x01(\x05R\x13minParticipantCount\x12-\n" +
	"\x12matchmaking_config\x18\x11 \x01(\tR\x11matchmakingConfig\x12W\n" +
	"\x14matching_key_creator\x18\x12 \x01(\x0e2%.nn.npln.ikaros.v1.MatchingKeyCreatorR\x12matchingKeyCreator\x12)\n" +
	"\x0ematching_hours\x18\x13 \x03(\x05B\x02\x10\x01R\rmatchingHours\x12&\n" +
	"\x0fmax_match_count\x18\x14 \x01(\x05R\rmaxMatchCount\x121\n" +
	"\x15max_daily_match_count\x18\x15 \x01(\x05R\x12maxDailyMatchCount\x120\n" +
	"\x14required_match_count\x18# \x01(\x05R\x12requiredMatchCount\x12 \n" +
	"\vmaintenance\x18\x16 \x01(\x05R\vmaintenance\x123\n" +
	"\x15explicit_finalization\x18\x17 \x01(\bR\x14explicitFinalization\x12C\n" +
	"\x10application_data\x18\x18 \x01(\v2\x18.nn.npln.common.MapValueR\x0fapplicationData\x12;\n" +
	"\vcreate_time\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18$ \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12P\n" +
	"\x16start_participate_time\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\x14startParticipateTime\x12L\n" +
	"\x14end_participate_time\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\x12endParticipateTime\x12F\n" +
	"\x11start_battle_time\x18\x1c \x01(\v2\x1a.google.protobuf.TimestampR\x0fstartBattleTime\x12B\n" +
	"\x0fend_battle_time\x18\x1d \x01(\v2\x1a.google.protobuf.TimestampR\rendBattleTime\x12A\n" +
	"\x0eaggregate_time\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\raggregateTime\x12?\n" +
	"\rfinalize_time\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\ffinalizeTime\x12+\n" +
	"\x11owner_participant\x18  \x01(\tR\x10ownerParticipant\x1a=\n" +
	"\x0fMainTitlesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eSubTitlesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x10CompetitionAlias\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vcompetition\x18\x02 \x01(\tR\vcompetition\"Z\n" +
	"\x1cCompetitionAlternativeResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12\x12\n" +
	"\x04etag\x18c \x01(\tR\x04etag\"\xab\x01\n" +
	"\x15CompetitionInvitation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\finvitee_type\x18\x02 \x01(\x0e2\x1e.nn.npln.ikaros.v1.InviteeTypeR\vinviteeType\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\xaa\x05\n" +
	"\x17CompetitionNotification\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\vupdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x12\n" +
	"\x04etag\x18c \x01(\tR\x04etag\x12e\n" +
	"\ainvalid\x18\x03 \x01(\v2I.nn.npln.ikaros.v1.CompetitionNotification.CompetitionInvalidNotificationH\x00R\ainvalid\x12#\n" +
	"\fmatching_key\x18\x04 \x01(\tH\x00R\vmatchingKey\x12h\n" +
	"\bschedule\x18\x05 \x01(\v2J.nn.npln.ikaros.v1.CompetitionNotification.CompetitionScheduleNotificationH\x00R\bschedule\x12q\n" +
	"\velimination\x18\x06 \x01(\v2M.nn.npln.ikaros.v1.CompetitionNotification.CompetitionEliminationNotificationH\x00R\velimination\x1a$\n" +
	"\"CompetitionEliminationNotification\x1a \n" +
	"\x1eCompetitionInvalidNotification\x1ai\n" +
	"\x1fCompetitionScheduleNotification\x12F\n" +
	"\x11start_battle_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0fstartBattleTimeB\x0e\n" +
	"\fnotification\"\x98\b\n" +
	"\x16CompetitionParticipant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x05R\x04slot\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"utc_offset\x18\x04 \x01(\tR\tutcOffset\x12-\n" +
	"\x12participant_binary\x18\x05 \x01(\fR\x11participantBinary\x12.\n" +
	"\x05state\x18\x06 \x01(\x0e2\x18.nn.npln.ikaros.v1.StateR\x05state\x12;\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12?\n" +
	"\ractivate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\factivateTime\x12C\n" +
	"\x0fdeactivate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0edeactivateTime\x12;\n" +
	"\vcancel_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"cancelTime\x12;\n" +
	"\vdelete_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deleteTime\x12\x1c\n" +
	"\tfinalized\x18\f \x01(\bR\tfinalized\x12\x16\n" +
	"\x06rating\x18\r \x01(\x05R\x06rating\x12\x12\n" +
	"\x04rank\x18\x0e \x01(\x05R\x04rank\x12\x1f\n" +
	"\vmatch_count\x18\x0f \x01(\x05R\n" +
	"matchCount\x12\x1b\n" +
	"\twin_count\x18\x10 \x01(\x05R\bwinCount\x12\x1d\n" +
	"\n" +
	"lose_count\x18\x11 \x01(\x05R\tloseCount\x12\x1d\n" +
	"\n" +
	"draw_count\x18\x12 \x01(\x05R\tdrawCount\x12)\n" +
	"\x10disconnect_count\x18\x13 \x01(\x05R\x0fdisconnectCount\x12(\n" +
	"\x10no_contest_count\x18\x14 \x01(\x05R\x0enoContestCount\x12(\n" +
	"\x10win_streak_count\x18\x15 \x01(\x05R\x0ewinStreakCount\x12*\n" +
	"\x11lose_streak_count\x18\x16 \x01(\x05R\x0floseStreakCount\x12\x14\n" +
	"\x05point\x18\x17 \x01(\x05R\x05point\x12\x1b\n" +
	"\tmax_point\x18\x18 \x01(\x05R\bmaxPoint\x12F\n" +
	"\bcategory\x18\x19 \x01(\x0e2*.nn.npln.ikaros.v1.CompetitionUserCategoryR\bcategory\x12\x12\n" +
	"\x04area\x18\x1a \x01(\x05R\x04area\"\xd7\a\n" +
	"\x0fCompetitionUser\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\bcategory\x18\x0e \x01(\x0e2*.nn.npln.ikaros.v1.CompetitionUserCategoryR\bcategory\x12\x1e\n" +
	"\n" +
	"birthmonth\x18\x02 \x01(\tR\n" +
	"birthmonth\x12\x12\n" +
	"\x04area\x18\x03 \x01(\x05R\x04area\x12#\n" +
	"\rlanguage_code\x18\x04 \x01(\tR\flanguageCode\x12@\n" +
	"\x1ccurrent_official_competition\x18\x05 \x01(\tR\x1acurrentOfficialCompetition\x12:\n" +
	"\x19last_official_competition\x18\x06 \x01(\tR\x17lastOfficialCompetition\x12@\n" +
	"\x1ccurrent_friendly_competition\x18\a \x01(\tR\x1acurrentFriendlyCompetition\x12:\n" +
	"\x19last_friendly_competition\x18\b \x01(\tR\x17lastFriendlyCompetition\x12K\n" +
	"\"current_ranked_singles_competition\x18\x0f \x01(\tR\x1fcurrentRankedSinglesCompetition\x12E\n" +
	"\x1flast_ranked_singles_competition\x18\x10 \x01(\tR\x1clastRankedSinglesCompetition\x12K\n" +
	"\"current_ranked_doubles_competition\x18\x11 \x01(\tR\x1fcurrentRankedDoublesCompetition\x12E\n" +
	"\x1flast_ranked_doubles_competition\x18\x12 \x01(\tR\x1clastRankedDoublesCompetition\x12Q\n" +
	"\fbattle_stats\x18\r \x01(\v2..nn.npln.ikaros.v1.CompetitionUser.BattleStatsR\vbattleStats\x12;\n" +
	"\vcreate_time\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x1a[\n" +
	"\vBattleStats\x12!\n" +
	"\fbattle_count\x18\x01 \x01(\x05R\vbattleCount\x12)\n" +
	"\x10disconnect_count\x18\x02 \x01(\x05R\x0fdisconnectCount\"Q\n" +
	"\x1bCompetitionUserBattleRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"disconnect\x18\x02 \x01(\bR\n" +
	"disconnect\"\xcc\x01\n" +
	"\x14PersonalBattleResult\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x127\n" +
	"\x06result\x18\x02 \x01(\x0e2\x1f.nn.npln.ikaros.v1.BattleResultR\x06result\x12=\n" +
	"\bbehavior\x18\x03 \x01(\x0e2!.nn.npln.ikaros.v1.BattleBehaviorR\bbehavior\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05point\x18\x05 \x01(\x05R\x05point*\xbf\x01\n" +
	"\x0eBattleBehavior\x12\x1f\n" +
	"\x1bBATTLE_BEHAVIOR_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13BEHAVIOR_SUCCESSFUL\x10\x00\x12\x19\n" +
	"\x15BEHAVIOR_DISCONNECTED\x10\x01\x12\x14\n" +
	"\x10BEHAVIOR_CHEATED\x10\x02\x12%\n" +
	"!BEHAVIOR_DISCONNECTED_AND_CHEATED\x10\x03\x12\x17\n" +
	"\x13BEHAVIOR_NO_CONTEST\x10\x04\x1a\x02\x10\x01*z\n" +
	"\fBattleResult\x12\x1d\n" +
	"\x19BATTLE_RESULT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vBATTLE_LOSE\x10\x00\x12\x0e\n" +
	"\n" +
	"BATTLE_WIN\x10\x01\x12\x0f\n" +
	"\vBATTLE_DRAW\x10\x02\x12\x15\n" +
	"\x11BATTLE_NO_CONTEST\x10\x03\x1a\x02\x10\x01*\x83\x01\n" +
	"\x0fCompetitionType\x12 \n" +
	"\x1cCOMPETITION_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bOFFICIAL\x10\x01\x12\f\n" +
	"\bFRIENDLY\x10\x02\x12\x12\n" +
	"\x0eRANKED_SINGLES\x10\x03\x12\x12\n" +
	"\x0eRANKED_DOUBLES\x10\x04\x12\n" +
	"\n" +
	"\x06CASUAL\x10\x05*h\n" +
	"\x17CompetitionUserCategory\x12)\n" +
	"%COMPETITION_USER_CATEGORY_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06JUNIOR\x10\x01\x12\n" +
	"\n" +
	"\x06SENIOR\x10\x02\x12\n" +
	"\n" +
	"\x06MASTER\x10\x03*S\n" +
	"\x0fCompetitionView\x12 \n" +
	"\x1cCOMPETITION_VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\b\n" +
	"\x04FULL\x10\x02\x12\t\n" +
	"\x05SMALL\x10\x03*F\n" +
	"\vInviteeType\x12\x1c\n" +
	"\x18INVITEE_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PLAYER\x10\x01\x12\r\n" +
	"\tSPECTATOR\x10\x02*T\n" +
	"\x12MatchingKeyCreator\x12$\n" +
	" MATCHING_KEY_CREATOR_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06SERVER\x10\x01\x12\f\n" +
	"\bOPERATOR\x10\x02*N\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\x16PERMISSION_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05OWNER\x10\x01\x12\f\n" +
	"\bINVITEES\x10\x02\x12\v\n" +
	"\aANYBODY\x10\x03*b\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bACCEPTED\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\f\n" +
	"\bINACTIVE\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04\x12\v\n" +
	"\aDELETED\x10\x05B8Z6npln.nintendo.net/npln-practice/proto/ikaros/v1;ikarosb\x06proto3"

var (
	file_proto_ikaros_v1_resources_proto_rawDescOnce sync.Once
	file_proto_ikaros_v1_resources_proto_rawDescData []byte
)

func file_proto_ikaros_v1_resources_proto_rawDescGZIP() []byte {
	file_proto_ikaros_v1_resources_proto_rawDescOnce.Do(func() {
		file_proto_ikaros_v1_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ikaros_v1_resources_proto_rawDesc), len(file_proto_ikaros_v1_resources_proto_rawDesc)))
	})
	return file_proto_ikaros_v1_resources_proto_rawDescData
}

var file_proto_ikaros_v1_resources_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_proto_ikaros_v1_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_ikaros_v1_resources_proto_goTypes = []any{
	(BattleBehavior)(0),                  // 0: nn.npln.ikaros.v1.BattleBehavior
	(BattleResult)(0),                    // 1: nn.npln.ikaros.v1.BattleResult
	(CompetitionType)(0),                 // 2: nn.npln.ikaros.v1.CompetitionType
	(CompetitionUserCategory)(0),         // 3: nn.npln.ikaros.v1.CompetitionUserCategory
	(CompetitionView)(0),                 // 4: nn.npln.ikaros.v1.CompetitionView
	(InviteeType)(0),                     // 5: nn.npln.ikaros.v1.InviteeType
	(MatchingKeyCreator)(0),              // 6: nn.npln.ikaros.v1.MatchingKeyCreator
	(Permission)(0),                      // 7: nn.npln.ikaros.v1.Permission
	(State)(0),                           // 8: nn.npln.ikaros.v1.State
	(*BattleDataLog)(nil),                // 9: nn.npln.ikaros.v1.BattleDataLog
	(*BattleReport)(nil),                 // 10: nn.npln.ikaros.v1.BattleReport
	(*Competition)(nil),                  // 11: nn.npln.ikaros.v1.Competition
	(*CompetitionAlias)(nil),             // 12: nn.npln.ikaros.v1.CompetitionAlias
	(*CompetitionAlternativeResult)(nil), // 13: nn.npln.ikaros.v1.CompetitionAlternativeResult
	(*CompetitionInvitation)(nil),        // 14: nn.npln.ikaros.v1.CompetitionInvitation
	(*CompetitionNotification)(nil),      // 15: nn.npln.ikaros.v1.CompetitionNotification
	(*CompetitionParticipant)(nil),       // 16: nn.npln.ikaros.v1.CompetitionParticipant
	(*CompetitionUser)(nil),              // 17: nn.npln.ikaros.v1.CompetitionUser
	(*CompetitionUserBattleRecord)(nil),  // 18: nn.npln.ikaros.v1.CompetitionUserBattleRecord
	(*PersonalBattleResult)(nil),         // 19: nn.npln.ikaros.v1.PersonalBattleResult
	nil,                                  // 20: nn.npln.ikaros.v1.Competition.MainTitlesEntry
	nil,                                  // 21: nn.npln.ikaros.v1.Competition.SubTitlesEntry
	(*CompetitionNotification_CompetitionEliminationNotification)(nil), // 22: nn.npln.ikaros.v1.CompetitionNotification.CompetitionEliminationNotification
	(*CompetitionNotification_CompetitionInvalidNotification)(nil),     // 23: nn.npln.ikaros.v1.CompetitionNotification.CompetitionInvalidNotification
	(*CompetitionNotification_CompetitionScheduleNotification)(nil),    // 24: nn.npln.ikaros.v1.CompetitionNotification.CompetitionScheduleNotification
	(*CompetitionUser_BattleStats)(nil),                                // 25: nn.npln.ikaros.v1.CompetitionUser.BattleStats
	(*timestamppb.Timestamp)(nil),                                      // 26: google.protobuf.Timestamp
	(*common.MapValue)(nil),                                            // 27: nn.npln.common.MapValue
}
var file_proto_ikaros_v1_resources_proto_depIdxs = []int32{
	2,  // 0: nn.npln.ikaros.v1.BattleDataLog.competition_type:type_name -> nn.npln.ikaros.v1.CompetitionType
	19, // 1: nn.npln.ikaros.v1.BattleDataLog.normalized_battle_results:type_name -> nn.npln.ikaros.v1.PersonalBattleResult
	26, // 2: nn.npln.ikaros.v1.BattleDataLog.create_time:type_name -> google.protobuf.Timestamp
	10, // 3: nn.npln.ikaros.v1.BattleDataLog.battle_reports:type_name -> nn.npln.ikaros.v1.BattleReport
	19, // 4: nn.npln.ikaros.v1.BattleReport.personal_battle_results:type_name -> nn.npln.ikaros.v1.PersonalBattleResult
	2,  // 5: nn.npln.ikaros.v1.Competition.competition_type:type_name -> nn.npln.ikaros.v1.CompetitionType
	20, // 6: nn.npln.ikaros.v1.Competition.main_titles:type_name -> nn.npln.ikaros.v1.Competition.MainTitlesEntry
	21, // 7: nn.npln.ikaros.v1.Competition.sub_titles:type_name -> nn.npln.ikaros.v1.Competition.SubTitlesEntry
	7,  // 8: nn.npln.ikaros.v1.Competition.read_permission:type_name -> nn.npln.ikaros.v1.Permission
	7,  // 9: nn.npln.ikaros.v1.Competition.write_permission:type_name -> nn.npln.ikaros.v1.Permission
	3,  // 10: nn.npln.ikaros.v1.Competition.participant_categories:type_name -> nn.npln.ikaros.v1.CompetitionUserCategory
	6,  // 11: nn.npln.ikaros.v1.Competition.matching_key_creator:type_name -> nn.npln.ikaros.v1.MatchingKeyCreator
	27, // 12: nn.npln.ikaros.v1.Competition.application_data:type_name -> nn.npln.common.MapValue
	26, // 13: nn.npln.ikaros.v1.Competition.create_time:type_name -> google.protobuf.Timestamp
	26, // 14: nn.npln.ikaros.v1.Competition.update_time:type_name -> google.protobuf.Timestamp
	26, // 15: nn.npln.ikaros.v1.Competition.start_participate_time:type_name -> google.protobuf.Timestamp
	26, // 16: nn.npln.ikaros.v1.Competition.end_participate_time:type_name -> google.protobuf.Timestamp
	26, // 17: nn.npln.ikaros.v1.Competition.start_battle_time:type_name -> google.protobuf.Timestamp
	26, // 18: nn.npln.ikaros.v1.Competition.end_battle_time:type_name -> google.protobuf.Timestamp
	26, // 19: nn.npln.ikaros.v1.Competition.aggregate_time:type_name -> google.protobuf.Timestamp
	26, // 20: nn.npln.ikaros.v1.Competition.finalize_time:type_name -> google.protobuf.Timestamp
	5,  // 21: nn.npln.ikaros.v1.CompetitionInvitation.invitee_type:type_name -> nn.npln.ikaros.v1.InviteeType
	26, // 22: nn.npln.ikaros.v1.CompetitionInvitation.create_time:type_name -> google.protobuf.Timestamp
	26, // 23: nn.npln.ikaros.v1.CompetitionNotification.update_time:type_name -> google.protobuf.Timestamp
	23, // 24: nn.npln.ikaros.v1.CompetitionNotification.invalid:type_name -> nn.npln.ikaros.v1.CompetitionNotification.CompetitionInvalidNotification
	24, // 25: nn.npln.ikaros.v1.CompetitionNotification.schedule:type_name -> nn.npln.ikaros.v1.CompetitionNotification.CompetitionScheduleNotification
	22, // 26: nn.npln.ikaros.v1.CompetitionNotification.elimination:type_name -> nn.npln.ikaros.v1.CompetitionNotification.CompetitionEliminationNotification
	8,  // 27: nn.npln.ikaros.v1.CompetitionParticipant.state:type_name -> nn.npln.ikaros.v1.State
	26, // 28: nn.npln.ikaros.v1.CompetitionParticipant.create_time:type_name -> google.protobuf.Timestamp
	26, // 29: nn.npln.ikaros.v1.CompetitionParticipant.activate_time:type_name -> google.protobuf.Timestamp
	26, // 30: nn.npln.ikaros.v1.CompetitionParticipant.deactivate_time:type_name -> google.protobuf.Timestamp
	26, // 31: nn.npln.ikaros.v1.CompetitionParticipant.cancel_time:type_name -> google.protobuf.Timestamp
	26, // 32: nn.npln.ikaros.v1.CompetitionParticipant.delete_time:type_name -> google.protobuf.Timestamp
	3,  // 33: nn.npln.ikaros.v1.CompetitionParticipant.category:type_name -> nn.npln.ikaros.v1.CompetitionUserCategory
	3,  // 34: nn.npln.ikaros.v1.CompetitionUser.category:type_name -> nn.npln.ikaros.v1.CompetitionUserCategory
	25, // 35: nn.npln.ikaros.v1.CompetitionUser.battle_stats:type_name -> nn.npln.ikaros.v1.CompetitionUser.BattleStats
	26, // 36: nn.npln.ikaros.v1.CompetitionUser.create_time:type_name -> google.protobuf.Timestamp
	1,  // 37: nn.npln.ikaros.v1.PersonalBattleResult.result:type_name -> nn.npln.ikaros.v1.BattleResult
	0,  // 38: nn.npln.ikaros.v1.PersonalBattleResult.behavior:type_name -> nn.npln.ikaros.v1.BattleBehavior
	26, // 39: nn.npln.ikaros.v1.CompetitionNotification.CompetitionScheduleNotification.start_battle_time:type_name -> google.protobuf.Timestamp
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_proto_ikaros_v1_resources_proto_init() }
func file_proto_ikaros_v1_resources_proto_init() {
	if File_proto_ikaros_v1_resources_proto != nil {
		return
	}
	file_proto_ikaros_v1_resources_proto_msgTypes[6].OneofWrappers = []any{
		(*CompetitionNotification_Invalid)(nil),
		(*CompetitionNotification_MatchingKey)(nil),
		(*CompetitionNotification_Schedule)(nil),
		(*CompetitionNotification_Elimination)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ikaros_v1_resources_proto_rawDesc), len(file_proto_ikaros_v1_resources_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ikaros_v1_resources_proto_goTypes,
		DependencyIndexes: file_proto_ikaros_v1_resources_proto_depIdxs,
		EnumInfos:         file_proto_ikaros_v1_resources_proto_enumTypes,
		MessageInfos:      file_proto_ikaros_v1_resources_proto_msgTypes,
	}.Build()
	File_proto_ikaros_v1_resources_proto = out.File
	file_proto_ikaros_v1_resources_proto_goTypes = nil
	file_proto_ikaros_v1_resources_proto_depIdxs = nil
}
